name: janus

services:
  
  janus_core:
    build: .
    networks:
      trusted_network:
        ipv4_address: 192.168.1.254
      untrusted_network:
        ipv4_address: 192.168.0.254
      server_network:
        ipv4_address: 172.16.0.20
    environment:
        BENCHMARK_MODE: "0"
        BENCHMARK_SKIP_HANDLER: "0"
        BENCHMARK_PRINT_INTERVAL_MS: "1000"
        
        JANUS_WORKERS: "4"
    command: ./build/janus
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    entrypoint: ./entrypoint.sh
    depends_on:
      db:
        condition: service_healthy
      system_status_handler:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "grep -q '0' /proc/net/netfilter/nfnetlink_queue"]
      interval: 1s
      retries: 3
    volumes:
      - ./blacklists:/blacklists
      - ./dpi_rules.txt:/app/dpi_rules.txt
      - ./rules.json:/app/rules.json



  untrusted_1:
    build: .
    container_name: untrusted_1
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.0.254 && sleep infinity"
    volumes:
      - ./pcaps:/pcaps
    networks:
      untrusted_network:
        ipv4_address: 192.168.0.10
    depends_on:
      janus_core:
        condition: service_healthy



  untrusted_2:
    build: .
    container_name: untrusted_2
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.0.254"
    volumes:
      - ./pcaps:/pcaps
    networks:
      untrusted_network:
        ipv4_address: 192.168.0.12
    depends_on:
      janus_core:
        condition: service_healthy


  untrusted_3:
    build: .
    container_name: untrusted_3
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.0.254"
    volumes:
      - ./pcaps:/pcaps
    networks:
      untrusted_network:
        ipv4_address: 192.168.0.13
    depends_on:
      janus_core:
        condition: service_healthy

  trusted_1:
    build: .
    container_name: trusted_1
    cap_add:
      - NET_ADMIN
    command: >
          sh -c "ip route del default && ip route add default via 192.168.1.254 && python3 -u /app/trusted_sink.py"
    networks:
      trusted_network:
        ipv4_address: 192.168.1.20



  system_status_handler:
    build: ./system_status_handler
    container_name: system_status_handler
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: janus
      PGUSER: janus_db
      PGPASSWORD: secret
      JANUS_CORE_CONTROL_HOST: janus_core
      JANUS_CORE_CONTROL_PORT: 50052
      JANUS_CORE_CONTROL_TIMEOUT_SEC: 3.0
      JANUS_RULES_PATH: /app/rules.json
      JANUS_IP_BLACKLIST_PATH: /blacklists/ip_blacklist.txt

    networks:
      server_network:
        ipv4_address: 172.16.0.30
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import sys, urllib.request; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/healthz').status == 200 else 1)"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    ports:
      - "8000:8000"
      - "50051:50051"
    volumes:
      - ./rules.json:/app/rules.json
      - ./db-init:/app/db-init
      - ./blacklists:/blacklists


  frontend:
    build:
      context: ./frontend
    container_name: janus_frontend
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    networks:
      server_network:
        ipv4_address: 172.16.0.50
    depends_on:
      system_status_handler:
        condition: service_healthy
  

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: janus_db
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: janus
    networks:
      server_network:
        ipv4_address: 172.16.0.10
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U janus_db -d janus" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql
      - ./db-init:/docker-entrypoint-initdb.d

  trusted_bench:
    build: .
    container_name: trusted_bench
    profiles: ["bench"]
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default &&
             ip route add default via 192.168.1.254 &&
             python3 -u /app/trusted_bench.py"
    environment:
      PORT_BASE: "8080"
      PORT_COUNT: "64"
    networks:
      trusted_network:
        ipv4_address: 192.168.1.30
    depends_on:
      janus_core:
        condition: service_healthy

  # bench_sender:
  #   build: .
  #   profiles: ["bench"]
  #   cap_add:
  #     - NET_ADMIN
  #   command: >
  #     sh -c "ip route del default &&
  #            ip route add default via 192.168.0.254 &&
  #            ./build/bench_mix_sender"
  #   environment:
  #     DEST_IP: "192.168.1.30"
  #     PORT_BASE: "8080"
  #     THREADS: "8"
  #     TCP_CONNECTIONS_PER_THREAD: "128"
  #     UDP_SOCKETS_PER_THREAD: "64"

  #     DURATION_SEC: "60"
  #     PORT_COUNT: "64"
  #     PAYLOAD_SIZE: "700"
  #     FRAG_PARTS: "4"
  #     PAUSE_US: "0"

  #     TCP_NODELAY: "1"
  #     SNDBUF_BYTES: "1048576"

  #     W_TCP_SAFE: "22"
  #     W_TCP_FLAG: "18"
  #     W_TCP_BLOCK: "20"
  #     W_UDP_SAFE: "10"
  #     W_UDP_FLAG: "12"
  #     W_UDP_BLOCK: "8"
  #     W_FRAG_SAFE: "5"
  #     W_FRAG_FLAG: "3"
  #     W_FRAG_BLOCK: "2"
  #   networks:
  #     untrusted_network: {}
  #   depends_on:
  #     janus_core:
  #       condition: service_healthy
  #     trusted_bench:
  #       condition: service_started


networks:
  untrusted_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

  trusted_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
volumes:
  pgdata:


