name: janus

services:
  #Core
  janus_core:
    build: .
    networks:
      trusted_network:
        ipv4_address: 192.168.1.254
      untrusted_network:
        ipv4_address: 192.168.0.254
    command: ./build/janus
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    entrypoint: ./entrypoint.sh
    healthcheck:
      test: [ "CMD", "sh", "-c", "grep -q '0' /proc/net/netfilter/nfnetlink_queue" ]
      interval: 1s
      #timeout: 2s
      retries: 3
      #start_period: 2s
    volumes:
      - ./blacklists:/blacklists
      - ./dpi_rules.txt:/app/dpi_rules.txt
      - ./icd.json:/app/icd.json

  #Untrusted 1
  untrusted_1:
    build: .
    container_name: untrusted_1
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.0.254 && ./build/main&&sleep infinity"
    volumes:
      - ./pcaps:/pcaps
    networks:
      untrusted_network:
        ipv4_address: 192.168.0.10
    depends_on:
      janus_core:
        condition: service_healthy
  untrusted_2:
    build: .
    container_name: untrusted_2
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.0.254 && ./build/main_2"
    volumes:
      - ./pcaps:/pcaps
    networks:
      untrusted_network:
        ipv4_address: 192.168.0.12
    depends_on:
      janus_core:
        condition: service_healthy
  untrusted_3:
    build: .
    container_name: untrusted_3
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.0.254 && ./build/main_3"
    volumes:
      - ./pcaps:/pcaps
    networks:
      untrusted_network:
        ipv4_address: 192.168.0.13
    depends_on:
      janus_core:
        condition: service_healthy

  #Trusted 1
  # sh -c "ip route del default && ip route add default via 192.168.1.254 && sleep infinity"
  # > /dev/null
  trusted_1:
    build: .
    container_name: trusted_1
    cap_add:
      - NET_ADMIN
    command: >
      sh -c "ip route del default && ip route add default via 192.168.1.254 && nc -lk -p 8080" 
    networks:
      trusted_network:
        ipv4_address: 192.168.1.20
        services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  volumes:
  pgdata:
    # portainer:
    #   image: portainer/portainer-ce:latest
    #   ports:
    #     - "9443:9443"
    #   volumes:
    #     - data:/data
    #     - /var/run/docker.sock:/var/run/docker.sock
    #   restart: unless-stopped

networks:
  untrusted_network:
    driver: bridge
    #internal: true
    ipam:
      config:
        - subnet: 192.168.0.0/24

  trusted_network:
    driver: bridge
    #internal: true
    ipam:
      config:
        - subnet: 192.168.1.0/24
volumes:
  data:
