# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus_packet.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'janus_packet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import janus_common_pb2 as janus__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12janus_packet.proto\x12\x0cjanus.packet\x1a\x12janus_common.proto\"\xb7\x02\n\x0ePacketMetadata\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\tpacket_id\x18\x02 \x01(\r\x12\x10\n\x08queue_id\x18\x03 \x01(\r\x12\x12\n\nts_unix_ms\x18\x04 \x01(\x04\x12\x16\n\x0epayload_length\x18\x05 \x01(\r\x12\x14\n\x0ctotal_length\x18\x06 \x01(\r\x12(\n\x08protocol\x18\x07 \x01(\x0e\x32\x16.janus.common.Protocol\x12&\n\x06source\x18\x08 \x01(\x0b\x32\x16.janus.common.Endpoint\x12+\n\x0b\x64\x65stination\x18\t \x01(\x0b\x32\x16.janus.common.Endpoint\x12\x15\n\ris_fragmented\x18\n \x01(\x08\x12\x16\n\x0eis_reassembled\x18\x0b \x01(\x08\"\x8c\x01\n\x14PreprocessingMessage\x12.\n\x08metadata\x18\x01 \x01(\x0b\x32\x1c.janus.packet.PacketMetadata\x12\x15\n\rparser_status\x18\x02 \x01(\t\x12\x14\n\x0cparser_notes\x18\x03 \x01(\t\x12\x17\n\x0fpayload_preview\x18\x04 \x01(\x0c\"\xbf\x03\n\x13PacketDecisionEvent\x12.\n\x08metadata\x18\x01 \x01(\x0b\x32\x1c.janus.packet.PacketMetadata\x12&\n\x07verdict\x18\x02 \x01(\x0e\x32\x15.janus.common.Verdict\x12\x0f\n\x07\x66lagged\x18\x03 \x01(\x08\x12\x11\n\tinspected\x18\x04 \x01(\x08\x12(\n\trule_hits\x18\x05 \x03(\x0b\x32\x15.janus.common.RuleHit\x12\x12\n\nmatch_info\x18\x06 \x01(\t\x12\x18\n\x10\x64\x65tection_source\x18\x07 \x01(\t\x12\x37\n\x10processing_trace\x18\x08 \x03(\x0b\x32\x1d.janus.common.ProcessingStamp\x12 \n\x18\x65nd_to_end_processing_us\x18\t \x01(\x04\x12\x11\n\tnode_name\x18\n \x01(\t\x12\x16\n\x0e\x63ontainer_name\x18\x0b \x01(\t\x12\x18\n\x10\x62lacklist_ip_hit\x18\x0c \x01(\x08\x12\x1a\n\x12\x62lacklist_port_hit\x18\r \x01(\x08\x12\x18\n\x10protocol_blocked\x18\x0e \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus_packet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PACKETMETADATA']._serialized_start=57
  _globals['_PACKETMETADATA']._serialized_end=368
  _globals['_PREPROCESSINGMESSAGE']._serialized_start=371
  _globals['_PREPROCESSINGMESSAGE']._serialized_end=511
  _globals['_PACKETDECISIONEVENT']._serialized_start=514
  _globals['_PACKETDECISIONEVENT']._serialized_end=961
# @@protoc_insertion_point(module_scope)
