# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: janus_common.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'janus_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12janus_common.proto\x12\x0cjanus.common\"$\n\x08\x45ndpoint\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\"\xc9\x01\n\x07RuleHit\x12\x0f\n\x07rule_id\x18\x01 \x01(\x05\x12\x11\n\trule_name\x18\x02 \x01(\t\x12\x11\n\trule_desc\x18\x03 \x01(\t\x12(\n\x08protocol\x18\x04 \x01(\x0e\x32\x16.janus.common.Protocol\x12(\n\x06\x61\x63tion\x18\x05 \x01(\x0e\x32\x18.janus.common.RuleAction\x12\x13\n\x0boffset_mode\x18\x06 \x01(\t\x12\x0e\n\x06offset\x18\x07 \x01(\r\x12\x0e\n\x06length\x18\x08 \x01(\r\"\x93\x01\n\x0fProcessingStamp\x12(\n\x05stage\x18\x01 \x01(\x0e\x32\x19.janus.common.EngineStage\x12\x17\n\x0fstarted_unix_ms\x18\x02 \x01(\x04\x12\x18\n\x10\x66inished_unix_ms\x18\x03 \x01(\x04\x12\x13\n\x0b\x64uration_us\x18\x04 \x01(\x04\x12\x0e\n\x06status\x18\x05 \x01(\t*\x81\x01\n\x08Protocol\x12\x18\n\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n\x0cPROTOCOL_ANY\x10\x01\x12\x10\n\x0cPROTOCOL_TCP\x10\x02\x12\x10\n\x0cPROTOCOL_UDP\x10\x03\x12\x11\n\rPROTOCOL_HTTP\x10\x04\x12\x12\n\x0ePROTOCOL_OTHER\x10\x05*G\n\x07Verdict\x12\x17\n\x13VERDICT_UNSPECIFIED\x10\x00\x12\x11\n\rVERDICT_ALLOW\x10\x01\x12\x10\n\x0cVERDICT_DROP\x10\x02*m\n\nRuleAction\x12\x1b\n\x17RULE_ACTION_UNSPECIFIED\x10\x00\x12\x15\n\x11RULE_ACTION_ALLOW\x10\x01\x12\x14\n\x10RULE_ACTION_FLAG\x10\x02\x12\x15\n\x11RULE_ACTION_BLOCK\x10\x03*\x9e\x02\n\x0b\x45ngineStage\x12\x1c\n\x18\x45NGINE_STAGE_UNSPECIFIED\x10\x00\x12\x1b\n\x17\x45NGINE_STAGE_PREPROCESS\x10\x01\x12\x17\n\x13\x45NGINE_STAGE_POLICY\x10\x02\x12\x1e\n\x1a\x45NGINE_STAGE_VECTOR_FILTER\x10\x03\x12\x16\n\x12\x45NGINE_STAGE_REGEX\x10\x04\x12\x14\n\x10\x45NGINE_STAGE_AHO\x10\x05\x12\x14\n\x10\x45NGINE_STAGE_DPI\x10\x06\x12\x1e\n\x1a\x45NGINE_STAGE_ENCAPSULATION\x10\x07\x12\x1d\n\x19\x45NGINE_STAGE_TRANSMISSION\x10\x08\x12\x18\n\x14\x45NGINE_STAGE_LOGGING\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'janus_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTOCOL']._serialized_start=429
  _globals['_PROTOCOL']._serialized_end=558
  _globals['_VERDICT']._serialized_start=560
  _globals['_VERDICT']._serialized_end=631
  _globals['_RULEACTION']._serialized_start=633
  _globals['_RULEACTION']._serialized_end=742
  _globals['_ENGINESTAGE']._serialized_start=745
  _globals['_ENGINESTAGE']._serialized_end=1031
  _globals['_ENDPOINT']._serialized_start=36
  _globals['_ENDPOINT']._serialized_end=72
  _globals['_RULEHIT']._serialized_start=75
  _globals['_RULEHIT']._serialized_end=276
  _globals['_PROCESSINGSTAMP']._serialized_start=279
  _globals['_PROCESSINGSTAMP']._serialized_end=426
# @@protoc_insertion_point(module_scope)
