name: janus

services:

  untrusted_pc:
    image: alpine:latest
    networks:
      - untrusted_network
  trusted_pc:
    image: alpine:latest
    networks:
      - trusted_network
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped





networks:
  untrusted_network:
    driver: bridge
  trusted_network:
    driver: bridge

volumes:
  data:

