// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: janus_common.proto
// Protobuf C++ Version: 6.33.1

#ifndef janus_5fcommon_2eproto_2epb_2eh
#define janus_5fcommon_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_janus_5fcommon_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_janus_5fcommon_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_janus_5fcommon_2eproto;
}  // extern "C"
namespace janus {
namespace common {
enum EngineStage : int;
extern const uint32_t EngineStage_internal_data_[];
enum Protocol : int;
extern const uint32_t Protocol_internal_data_[];
enum RuleAction : int;
extern const uint32_t RuleAction_internal_data_[];
enum Verdict : int;
extern const uint32_t Verdict_internal_data_[];
class Endpoint;
struct EndpointDefaultTypeInternal;
extern EndpointDefaultTypeInternal _Endpoint_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Endpoint_class_data_;
class ProcessingStamp;
struct ProcessingStampDefaultTypeInternal;
extern ProcessingStampDefaultTypeInternal _ProcessingStamp_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProcessingStamp_class_data_;
class RuleHit;
struct RuleHitDefaultTypeInternal;
extern RuleHitDefaultTypeInternal _RuleHit_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RuleHit_class_data_;
}  // namespace common
}  // namespace janus
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::janus::common::EngineStage_internal_data_>
    internal::EnumTraitsImpl::value<::janus::common::EngineStage>;
template <>
internal::EnumTraitsT<::janus::common::Protocol_internal_data_>
    internal::EnumTraitsImpl::value<::janus::common::Protocol>;
template <>
internal::EnumTraitsT<::janus::common::RuleAction_internal_data_>
    internal::EnumTraitsImpl::value<::janus::common::RuleAction>;
template <>
internal::EnumTraitsT<::janus::common::Verdict_internal_data_>
    internal::EnumTraitsImpl::value<::janus::common::Verdict>;
}  // namespace protobuf
}  // namespace google

namespace janus {
namespace common {
enum Protocol : int {
  PROTOCOL_UNSPECIFIED = 0,
  PROTOCOL_ANY = 1,
  PROTOCOL_TCP = 2,
  PROTOCOL_UDP = 3,
  PROTOCOL_HTTP = 4,
  PROTOCOL_OTHER = 5,
  Protocol_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Protocol_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Protocol_internal_data_[];
inline constexpr Protocol Protocol_MIN =
    static_cast<Protocol>(0);
inline constexpr Protocol Protocol_MAX =
    static_cast<Protocol>(5);
inline bool Protocol_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int Protocol_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Protocol_descriptor();
template <typename T>
const ::std::string& Protocol_Name(T value) {
  static_assert(::std::is_same<T, Protocol>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Protocol_Name().");
  return Protocol_Name(static_cast<Protocol>(value));
}
template <>
inline const ::std::string& Protocol_Name(Protocol value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Protocol_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool Protocol_Parse(
    ::absl::string_view name, Protocol* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Protocol>(Protocol_descriptor(), name,
                                           value);
}
enum Verdict : int {
  VERDICT_UNSPECIFIED = 0,
  VERDICT_ALLOW = 1,
  VERDICT_DROP = 2,
  Verdict_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Verdict_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Verdict_internal_data_[];
inline constexpr Verdict Verdict_MIN =
    static_cast<Verdict>(0);
inline constexpr Verdict Verdict_MAX =
    static_cast<Verdict>(2);
inline bool Verdict_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Verdict_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Verdict_descriptor();
template <typename T>
const ::std::string& Verdict_Name(T value) {
  static_assert(::std::is_same<T, Verdict>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Verdict_Name().");
  return Verdict_Name(static_cast<Verdict>(value));
}
template <>
inline const ::std::string& Verdict_Name(Verdict value) {
  return ::google::protobuf::internal::NameOfDenseEnum<Verdict_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool Verdict_Parse(
    ::absl::string_view name, Verdict* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<Verdict>(Verdict_descriptor(), name,
                                           value);
}
enum RuleAction : int {
  RULE_ACTION_UNSPECIFIED = 0,
  RULE_ACTION_ALLOW = 1,
  RULE_ACTION_FLAG = 2,
  RULE_ACTION_BLOCK = 3,
  RuleAction_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RuleAction_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RuleAction_internal_data_[];
inline constexpr RuleAction RuleAction_MIN =
    static_cast<RuleAction>(0);
inline constexpr RuleAction RuleAction_MAX =
    static_cast<RuleAction>(3);
inline bool RuleAction_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int RuleAction_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RuleAction_descriptor();
template <typename T>
const ::std::string& RuleAction_Name(T value) {
  static_assert(::std::is_same<T, RuleAction>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to RuleAction_Name().");
  return RuleAction_Name(static_cast<RuleAction>(value));
}
template <>
inline const ::std::string& RuleAction_Name(RuleAction value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RuleAction_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool RuleAction_Parse(
    ::absl::string_view name, RuleAction* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RuleAction>(RuleAction_descriptor(), name,
                                           value);
}
enum EngineStage : int {
  ENGINE_STAGE_UNSPECIFIED = 0,
  ENGINE_STAGE_PREPROCESS = 1,
  ENGINE_STAGE_POLICY = 2,
  ENGINE_STAGE_VECTOR_FILTER = 3,
  ENGINE_STAGE_REGEX = 4,
  ENGINE_STAGE_AHO = 5,
  ENGINE_STAGE_DPI = 6,
  ENGINE_STAGE_ENCAPSULATION = 7,
  ENGINE_STAGE_TRANSMISSION = 8,
  ENGINE_STAGE_LOGGING = 9,
  EngineStage_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  EngineStage_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t EngineStage_internal_data_[];
inline constexpr EngineStage EngineStage_MIN =
    static_cast<EngineStage>(0);
inline constexpr EngineStage EngineStage_MAX =
    static_cast<EngineStage>(9);
inline bool EngineStage_IsValid(int value) {
  return 0 <= value && value <= 9;
}
inline constexpr int EngineStage_ARRAYSIZE = 9 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EngineStage_descriptor();
template <typename T>
const ::std::string& EngineStage_Name(T value) {
  static_assert(::std::is_same<T, EngineStage>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EngineStage_Name().");
  return EngineStage_Name(static_cast<EngineStage>(value));
}
template <>
inline const ::std::string& EngineStage_Name(EngineStage value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EngineStage_descriptor, 0, 9>(
      static_cast<int>(value));
}
inline bool EngineStage_Parse(
    ::absl::string_view name, EngineStage* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EngineStage>(EngineStage_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RuleHit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:janus.common.RuleHit) */ {
 public:
  inline RuleHit() : RuleHit(nullptr) {}
  ~RuleHit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RuleHit* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RuleHit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RuleHit(::google::protobuf::internal::ConstantInitialized);

  inline RuleHit(const RuleHit& from) : RuleHit(nullptr, from) {}
  inline RuleHit(RuleHit&& from) noexcept
      : RuleHit(nullptr, ::std::move(from)) {}
  inline RuleHit& operator=(const RuleHit& from) {
    CopyFrom(from);
    return *this;
  }
  inline RuleHit& operator=(RuleHit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RuleHit& default_instance() {
    return *reinterpret_cast<const RuleHit*>(
        &_RuleHit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RuleHit& a, RuleHit& b) { a.Swap(&b); }
  inline void Swap(RuleHit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RuleHit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RuleHit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RuleHit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RuleHit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RuleHit& from) { RuleHit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RuleHit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "janus.common.RuleHit"; }

  explicit RuleHit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RuleHit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RuleHit& from);
  RuleHit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RuleHit&& from) noexcept
      : RuleHit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRuleNameFieldNumber = 2,
    kRuleDescFieldNumber = 3,
    kOffsetModeFieldNumber = 6,
    kRuleIdFieldNumber = 1,
    kProtocolFieldNumber = 4,
    kActionFieldNumber = 5,
    kOffsetFieldNumber = 7,
    kLengthFieldNumber = 8,
  };
  // string rule_name = 2;
  void clear_rule_name() ;
  const ::std::string& rule_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rule_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rule_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rule_name();
  void set_allocated_rule_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rule_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rule_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rule_name();

  public:
  // string rule_desc = 3;
  void clear_rule_desc() ;
  const ::std::string& rule_desc() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rule_desc(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rule_desc();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rule_desc();
  void set_allocated_rule_desc(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rule_desc() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rule_desc(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rule_desc();

  public:
  // string offset_mode = 6;
  void clear_offset_mode() ;
  const ::std::string& offset_mode() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_offset_mode(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_offset_mode();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_offset_mode();
  void set_allocated_offset_mode(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_offset_mode() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_offset_mode(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_offset_mode();

  public:
  // int32 rule_id = 1;
  void clear_rule_id() ;
  ::int32_t rule_id() const;
  void set_rule_id(::int32_t value);

  private:
  ::int32_t _internal_rule_id() const;
  void _internal_set_rule_id(::int32_t value);

  public:
  // .janus.common.Protocol protocol = 4;
  void clear_protocol() ;
  ::janus::common::Protocol protocol() const;
  void set_protocol(::janus::common::Protocol value);

  private:
  ::janus::common::Protocol _internal_protocol() const;
  void _internal_set_protocol(::janus::common::Protocol value);

  public:
  // .janus.common.RuleAction action = 5;
  void clear_action() ;
  ::janus::common::RuleAction action() const;
  void set_action(::janus::common::RuleAction value);

  private:
  ::janus::common::RuleAction _internal_action() const;
  void _internal_set_action(::janus::common::RuleAction value);

  public:
  // uint32 offset = 7;
  void clear_offset() ;
  ::uint32_t offset() const;
  void set_offset(::uint32_t value);

  private:
  ::uint32_t _internal_offset() const;
  void _internal_set_offset(::uint32_t value);

  public:
  // uint32 length = 8;
  void clear_length() ;
  ::uint32_t length() const;
  void set_length(::uint32_t value);

  private:
  ::uint32_t _internal_length() const;
  void _internal_set_length(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:janus.common.RuleHit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   0, 66,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RuleHit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr rule_name_;
    ::google::protobuf::internal::ArenaStringPtr rule_desc_;
    ::google::protobuf::internal::ArenaStringPtr offset_mode_;
    ::int32_t rule_id_;
    int protocol_;
    int action_;
    ::uint32_t offset_;
    ::uint32_t length_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_janus_5fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RuleHit_class_data_;
// -------------------------------------------------------------------

class ProcessingStamp final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:janus.common.ProcessingStamp) */ {
 public:
  inline ProcessingStamp() : ProcessingStamp(nullptr) {}
  ~ProcessingStamp() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProcessingStamp* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProcessingStamp));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProcessingStamp(::google::protobuf::internal::ConstantInitialized);

  inline ProcessingStamp(const ProcessingStamp& from) : ProcessingStamp(nullptr, from) {}
  inline ProcessingStamp(ProcessingStamp&& from) noexcept
      : ProcessingStamp(nullptr, ::std::move(from)) {}
  inline ProcessingStamp& operator=(const ProcessingStamp& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessingStamp& operator=(ProcessingStamp&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessingStamp& default_instance() {
    return *reinterpret_cast<const ProcessingStamp*>(
        &_ProcessingStamp_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ProcessingStamp& a, ProcessingStamp& b) { a.Swap(&b); }
  inline void Swap(ProcessingStamp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessingStamp* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessingStamp* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProcessingStamp>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProcessingStamp& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProcessingStamp& from) { ProcessingStamp::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProcessingStamp* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "janus.common.ProcessingStamp"; }

  explicit ProcessingStamp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ProcessingStamp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ProcessingStamp& from);
  ProcessingStamp(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ProcessingStamp&& from) noexcept
      : ProcessingStamp(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStatusFieldNumber = 5,
    kStartedUnixMsFieldNumber = 2,
    kFinishedUnixMsFieldNumber = 3,
    kDurationUsFieldNumber = 4,
    kStageFieldNumber = 1,
  };
  // string status = 5;
  void clear_status() ;
  const ::std::string& status() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_status(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_status();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_status();
  void set_allocated_status(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_status() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_status(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  // uint64 started_unix_ms = 2;
  void clear_started_unix_ms() ;
  ::uint64_t started_unix_ms() const;
  void set_started_unix_ms(::uint64_t value);

  private:
  ::uint64_t _internal_started_unix_ms() const;
  void _internal_set_started_unix_ms(::uint64_t value);

  public:
  // uint64 finished_unix_ms = 3;
  void clear_finished_unix_ms() ;
  ::uint64_t finished_unix_ms() const;
  void set_finished_unix_ms(::uint64_t value);

  private:
  ::uint64_t _internal_finished_unix_ms() const;
  void _internal_set_finished_unix_ms(::uint64_t value);

  public:
  // uint64 duration_us = 4;
  void clear_duration_us() ;
  ::uint64_t duration_us() const;
  void set_duration_us(::uint64_t value);

  private:
  ::uint64_t _internal_duration_us() const;
  void _internal_set_duration_us(::uint64_t value);

  public:
  // .janus.common.EngineStage stage = 1;
  void clear_stage() ;
  ::janus::common::EngineStage stage() const;
  void set_stage(::janus::common::EngineStage value);

  private:
  ::janus::common::EngineStage _internal_stage() const;
  void _internal_set_stage(::janus::common::EngineStage value);

  public:
  // @@protoc_insertion_point(class_scope:janus.common.ProcessingStamp)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 43,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ProcessingStamp& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr status_;
    ::uint64_t started_unix_ms_;
    ::uint64_t finished_unix_ms_;
    ::uint64_t duration_us_;
    int stage_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_janus_5fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProcessingStamp_class_data_;
// -------------------------------------------------------------------

class Endpoint final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:janus.common.Endpoint) */ {
 public:
  inline Endpoint() : Endpoint(nullptr) {}
  ~Endpoint() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Endpoint* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Endpoint));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Endpoint(::google::protobuf::internal::ConstantInitialized);

  inline Endpoint(const Endpoint& from) : Endpoint(nullptr, from) {}
  inline Endpoint(Endpoint&& from) noexcept
      : Endpoint(nullptr, ::std::move(from)) {}
  inline Endpoint& operator=(const Endpoint& from) {
    CopyFrom(from);
    return *this;
  }
  inline Endpoint& operator=(Endpoint&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Endpoint& default_instance() {
    return *reinterpret_cast<const Endpoint*>(
        &_Endpoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Endpoint& a, Endpoint& b) { a.Swap(&b); }
  inline void Swap(Endpoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Endpoint* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Endpoint* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Endpoint>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Endpoint& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Endpoint& from) { Endpoint::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Endpoint* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "janus.common.Endpoint"; }

  explicit Endpoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Endpoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Endpoint& from);
  Endpoint(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Endpoint&& from) noexcept
      : Endpoint(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // string ip = 1;
  void clear_ip() ;
  const ::std::string& ip() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ip(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ip();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ip();
  void set_allocated_ip(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ip() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ip(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ip();

  public:
  // uint32 port = 2;
  void clear_port() ;
  ::uint32_t port() const;
  void set_port(::uint32_t value);

  private:
  ::uint32_t _internal_port() const;
  void _internal_set_port(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:janus.common.Endpoint)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 32,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Endpoint& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ip_;
    ::uint32_t port_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_janus_5fcommon_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Endpoint_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Endpoint

// string ip = 1;
inline void Endpoint::clear_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Endpoint::ip() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:janus.common.Endpoint.ip)
  return _internal_ip();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Endpoint::set_ip(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ip_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:janus.common.Endpoint.ip)
}
inline ::std::string* PROTOBUF_NONNULL Endpoint::mutable_ip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ip();
  // @@protoc_insertion_point(field_mutable:janus.common.Endpoint.ip)
  return _s;
}
inline const ::std::string& Endpoint::_internal_ip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_.Get();
}
inline void Endpoint::_internal_set_ip(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Endpoint::_internal_mutable_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Endpoint::release_ip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:janus.common.Endpoint.ip)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ip_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ip_.Set("", GetArena());
  }
  return released;
}
inline void Endpoint::set_allocated_ip(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ip_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_.IsDefault()) {
    _impl_.ip_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:janus.common.Endpoint.ip)
}

// uint32 port = 2;
inline void Endpoint::clear_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t Endpoint::port() const {
  // @@protoc_insertion_point(field_get:janus.common.Endpoint.port)
  return _internal_port();
}
inline void Endpoint::set_port(::uint32_t value) {
  _internal_set_port(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:janus.common.Endpoint.port)
}
inline ::uint32_t Endpoint::_internal_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_;
}
inline void Endpoint::_internal_set_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_ = value;
}

// -------------------------------------------------------------------

// RuleHit

// int32 rule_id = 1;
inline void RuleHit::clear_rule_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t RuleHit::rule_id() const {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.rule_id)
  return _internal_rule_id();
}
inline void RuleHit::set_rule_id(::int32_t value) {
  _internal_set_rule_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.rule_id)
}
inline ::int32_t RuleHit::_internal_rule_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rule_id_;
}
inline void RuleHit::_internal_set_rule_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_id_ = value;
}

// string rule_name = 2;
inline void RuleHit::clear_rule_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RuleHit::rule_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.rule_name)
  return _internal_rule_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RuleHit::set_rule_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.rule_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.rule_name)
}
inline ::std::string* PROTOBUF_NONNULL RuleHit::mutable_rule_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_rule_name();
  // @@protoc_insertion_point(field_mutable:janus.common.RuleHit.rule_name)
  return _s;
}
inline const ::std::string& RuleHit::_internal_rule_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rule_name_.Get();
}
inline void RuleHit::_internal_set_rule_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RuleHit::_internal_mutable_rule_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rule_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RuleHit::release_rule_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:janus.common.RuleHit.rule_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.rule_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rule_name_.Set("", GetArena());
  }
  return released;
}
inline void RuleHit::set_allocated_rule_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.rule_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rule_name_.IsDefault()) {
    _impl_.rule_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:janus.common.RuleHit.rule_name)
}

// string rule_desc = 3;
inline void RuleHit::clear_rule_desc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_desc_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RuleHit::rule_desc() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.rule_desc)
  return _internal_rule_desc();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RuleHit::set_rule_desc(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.rule_desc_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.rule_desc)
}
inline ::std::string* PROTOBUF_NONNULL RuleHit::mutable_rule_desc()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_rule_desc();
  // @@protoc_insertion_point(field_mutable:janus.common.RuleHit.rule_desc)
  return _s;
}
inline const ::std::string& RuleHit::_internal_rule_desc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rule_desc_.Get();
}
inline void RuleHit::_internal_set_rule_desc(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_desc_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RuleHit::_internal_mutable_rule_desc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rule_desc_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RuleHit::release_rule_desc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:janus.common.RuleHit.rule_desc)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.rule_desc_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rule_desc_.Set("", GetArena());
  }
  return released;
}
inline void RuleHit::set_allocated_rule_desc(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.rule_desc_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rule_desc_.IsDefault()) {
    _impl_.rule_desc_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:janus.common.RuleHit.rule_desc)
}

// .janus.common.Protocol protocol = 4;
inline void RuleHit::clear_protocol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::janus::common::Protocol RuleHit::protocol() const {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.protocol)
  return _internal_protocol();
}
inline void RuleHit::set_protocol(::janus::common::Protocol value) {
  _internal_set_protocol(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.protocol)
}
inline ::janus::common::Protocol RuleHit::_internal_protocol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::janus::common::Protocol>(_impl_.protocol_);
}
inline void RuleHit::_internal_set_protocol(::janus::common::Protocol value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.protocol_ = value;
}

// .janus.common.RuleAction action = 5;
inline void RuleHit::clear_action() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::janus::common::RuleAction RuleHit::action() const {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.action)
  return _internal_action();
}
inline void RuleHit::set_action(::janus::common::RuleAction value) {
  _internal_set_action(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.action)
}
inline ::janus::common::RuleAction RuleHit::_internal_action() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::janus::common::RuleAction>(_impl_.action_);
}
inline void RuleHit::_internal_set_action(::janus::common::RuleAction value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.action_ = value;
}

// string offset_mode = 6;
inline void RuleHit::clear_offset_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_mode_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& RuleHit::offset_mode() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.offset_mode)
  return _internal_offset_mode();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RuleHit::set_offset_mode(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.offset_mode_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.offset_mode)
}
inline ::std::string* PROTOBUF_NONNULL RuleHit::mutable_offset_mode()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_offset_mode();
  // @@protoc_insertion_point(field_mutable:janus.common.RuleHit.offset_mode)
  return _s;
}
inline const ::std::string& RuleHit::_internal_offset_mode() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_mode_.Get();
}
inline void RuleHit::_internal_set_offset_mode(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_mode_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RuleHit::_internal_mutable_offset_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.offset_mode_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RuleHit::release_offset_mode() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:janus.common.RuleHit.offset_mode)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.offset_mode_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.offset_mode_.Set("", GetArena());
  }
  return released;
}
inline void RuleHit::set_allocated_offset_mode(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.offset_mode_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.offset_mode_.IsDefault()) {
    _impl_.offset_mode_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:janus.common.RuleHit.offset_mode)
}

// uint32 offset = 7;
inline void RuleHit::clear_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t RuleHit::offset() const {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.offset)
  return _internal_offset();
}
inline void RuleHit::set_offset(::uint32_t value) {
  _internal_set_offset(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.offset)
}
inline ::uint32_t RuleHit::_internal_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_;
}
inline void RuleHit::_internal_set_offset(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = value;
}

// uint32 length = 8;
inline void RuleHit::clear_length() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::uint32_t RuleHit::length() const {
  // @@protoc_insertion_point(field_get:janus.common.RuleHit.length)
  return _internal_length();
}
inline void RuleHit::set_length(::uint32_t value) {
  _internal_set_length(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:janus.common.RuleHit.length)
}
inline ::uint32_t RuleHit::_internal_length() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.length_;
}
inline void RuleHit::_internal_set_length(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.length_ = value;
}

// -------------------------------------------------------------------

// ProcessingStamp

// .janus.common.EngineStage stage = 1;
inline void ProcessingStamp::clear_stage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::janus::common::EngineStage ProcessingStamp::stage() const {
  // @@protoc_insertion_point(field_get:janus.common.ProcessingStamp.stage)
  return _internal_stage();
}
inline void ProcessingStamp::set_stage(::janus::common::EngineStage value) {
  _internal_set_stage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:janus.common.ProcessingStamp.stage)
}
inline ::janus::common::EngineStage ProcessingStamp::_internal_stage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::janus::common::EngineStage>(_impl_.stage_);
}
inline void ProcessingStamp::_internal_set_stage(::janus::common::EngineStage value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.stage_ = value;
}

// uint64 started_unix_ms = 2;
inline void ProcessingStamp::clear_started_unix_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.started_unix_ms_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t ProcessingStamp::started_unix_ms() const {
  // @@protoc_insertion_point(field_get:janus.common.ProcessingStamp.started_unix_ms)
  return _internal_started_unix_ms();
}
inline void ProcessingStamp::set_started_unix_ms(::uint64_t value) {
  _internal_set_started_unix_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:janus.common.ProcessingStamp.started_unix_ms)
}
inline ::uint64_t ProcessingStamp::_internal_started_unix_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.started_unix_ms_;
}
inline void ProcessingStamp::_internal_set_started_unix_ms(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.started_unix_ms_ = value;
}

// uint64 finished_unix_ms = 3;
inline void ProcessingStamp::clear_finished_unix_ms() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.finished_unix_ms_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t ProcessingStamp::finished_unix_ms() const {
  // @@protoc_insertion_point(field_get:janus.common.ProcessingStamp.finished_unix_ms)
  return _internal_finished_unix_ms();
}
inline void ProcessingStamp::set_finished_unix_ms(::uint64_t value) {
  _internal_set_finished_unix_ms(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:janus.common.ProcessingStamp.finished_unix_ms)
}
inline ::uint64_t ProcessingStamp::_internal_finished_unix_ms() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.finished_unix_ms_;
}
inline void ProcessingStamp::_internal_set_finished_unix_ms(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.finished_unix_ms_ = value;
}

// uint64 duration_us = 4;
inline void ProcessingStamp::clear_duration_us() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_us_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t ProcessingStamp::duration_us() const {
  // @@protoc_insertion_point(field_get:janus.common.ProcessingStamp.duration_us)
  return _internal_duration_us();
}
inline void ProcessingStamp::set_duration_us(::uint64_t value) {
  _internal_set_duration_us(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:janus.common.ProcessingStamp.duration_us)
}
inline ::uint64_t ProcessingStamp::_internal_duration_us() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.duration_us_;
}
inline void ProcessingStamp::_internal_set_duration_us(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.duration_us_ = value;
}

// string status = 5;
inline void ProcessingStamp::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& ProcessingStamp::status() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:janus.common.ProcessingStamp.status)
  return _internal_status();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void ProcessingStamp::set_status(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.status_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:janus.common.ProcessingStamp.status)
}
inline ::std::string* PROTOBUF_NONNULL ProcessingStamp::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:janus.common.ProcessingStamp.status)
  return _s;
}
inline const ::std::string& ProcessingStamp::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_.Get();
}
inline void ProcessingStamp::_internal_set_status(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL ProcessingStamp::_internal_mutable_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.status_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE ProcessingStamp::release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:janus.common.ProcessingStamp.status)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.status_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.status_.Set("", GetArena());
  }
  return released;
}
inline void ProcessingStamp::set_allocated_status(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.status_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:janus.common.ProcessingStamp.status)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace janus


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::janus::common::Protocol> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::janus::common::Protocol>() {
  return ::janus::common::Protocol_descriptor();
}
template <>
struct is_proto_enum<::janus::common::Verdict> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::janus::common::Verdict>() {
  return ::janus::common::Verdict_descriptor();
}
template <>
struct is_proto_enum<::janus::common::RuleAction> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::janus::common::RuleAction>() {
  return ::janus::common::RuleAction_descriptor();
}
template <>
struct is_proto_enum<::janus::common::EngineStage> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::janus::common::EngineStage>() {
  return ::janus::common::EngineStage_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // janus_5fcommon_2eproto_2epb_2eh
