// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: janus_packet.proto
// Protobuf C++ Version: 6.33.1

#include "janus_packet.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace janus {
namespace packet {

inline constexpr PacketMetadata::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        event_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_{nullptr},
        destination_{nullptr},
        packet_id_{0u},
        queue_id_{0u},
        ts_unix_ms_{::uint64_t{0u}},
        payload_length_{0u},
        total_length_{0u},
        protocol_{static_cast< ::janus::common::Protocol >(0)},
        is_fragmented_{false},
        is_reassembled_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PacketMetadata::PacketMetadata(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PacketMetadata_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketMetadataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketMetadataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketMetadataDefaultTypeInternal() {}
  union {
    PacketMetadata _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketMetadataDefaultTypeInternal _PacketMetadata_default_instance_;

inline constexpr PreprocessingMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        parser_status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        parser_notes_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_preview_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        metadata_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR PreprocessingMessage::PreprocessingMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PreprocessingMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PreprocessingMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PreprocessingMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PreprocessingMessageDefaultTypeInternal() {}
  union {
    PreprocessingMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PreprocessingMessageDefaultTypeInternal _PreprocessingMessage_default_instance_;

inline constexpr PacketDecisionEvent::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rule_hits_{},
        processing_trace_{},
        match_info_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        detection_source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        node_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        container_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        metadata_{nullptr},
        verdict_{static_cast< ::janus::common::Verdict >(0)},
        flagged_{false},
        inspected_{false},
        blacklist_ip_hit_{false},
        blacklist_port_hit_{false},
        end_to_end_processing_us_{::uint64_t{0u}},
        protocol_blocked_{false} {}

template <typename>
PROTOBUF_CONSTEXPR PacketDecisionEvent::PacketDecisionEvent(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PacketDecisionEvent_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PacketDecisionEventDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PacketDecisionEventDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PacketDecisionEventDefaultTypeInternal() {}
  union {
    PacketDecisionEvent _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PacketDecisionEventDefaultTypeInternal _PacketDecisionEvent_default_instance_;
}  // namespace packet
}  // namespace janus
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_janus_5fpacket_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_janus_5fpacket_2eproto = nullptr;
const ::uint32_t
    TableStruct_janus_5fpacket_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_._has_bits_),
        14, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.event_id_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.packet_id_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.queue_id_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.ts_unix_ms_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.payload_length_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.total_length_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.protocol_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.source_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.destination_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.is_fragmented_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketMetadata, _impl_.is_reassembled_),
        0,
        3,
        4,
        5,
        6,
        7,
        8,
        1,
        2,
        9,
        10,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::janus::packet::PreprocessingMessage, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::janus::packet::PreprocessingMessage, _impl_.metadata_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PreprocessingMessage, _impl_.parser_status_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PreprocessingMessage, _impl_.parser_notes_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PreprocessingMessage, _impl_.payload_preview_),
        3,
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_._has_bits_),
        17, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.metadata_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.verdict_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.flagged_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.inspected_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.rule_hits_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.match_info_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.detection_source_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.processing_trace_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.end_to_end_processing_us_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.node_name_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.container_name_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.blacklist_ip_hit_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.blacklist_port_hit_),
        PROTOBUF_FIELD_OFFSET(::janus::packet::PacketDecisionEvent, _impl_.protocol_blocked_),
        6,
        7,
        8,
        9,
        0,
        2,
        3,
        1,
        12,
        4,
        5,
        10,
        11,
        13,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::janus::packet::PacketMetadata)},
        {25, sizeof(::janus::packet::PreprocessingMessage)},
        {36, sizeof(::janus::packet::PacketDecisionEvent)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::janus::packet::_PacketMetadata_default_instance_._instance,
    &::janus::packet::_PreprocessingMessage_default_instance_._instance,
    &::janus::packet::_PacketDecisionEvent_default_instance_._instance,
};
const char descriptor_table_protodef_janus_5fpacket_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022janus_packet.proto\022\014janus.packet\032\022janu"
    "s_common.proto\"\267\002\n\016PacketMetadata\022\020\n\010eve"
    "nt_id\030\001 \001(\t\022\021\n\tpacket_id\030\002 \001(\r\022\020\n\010queue_"
    "id\030\003 \001(\r\022\022\n\nts_unix_ms\030\004 \001(\004\022\026\n\016payload_"
    "length\030\005 \001(\r\022\024\n\014total_length\030\006 \001(\r\022(\n\010pr"
    "otocol\030\007 \001(\0162\026.janus.common.Protocol\022&\n\006"
    "source\030\010 \001(\0132\026.janus.common.Endpoint\022+\n\013"
    "destination\030\t \001(\0132\026.janus.common.Endpoin"
    "t\022\025\n\ris_fragmented\030\n \001(\010\022\026\n\016is_reassembl"
    "ed\030\013 \001(\010\"\214\001\n\024PreprocessingMessage\022.\n\010met"
    "adata\030\001 \001(\0132\034.janus.packet.PacketMetadat"
    "a\022\025\n\rparser_status\030\002 \001(\t\022\024\n\014parser_notes"
    "\030\003 \001(\t\022\027\n\017payload_preview\030\004 \001(\014\"\277\003\n\023Pack"
    "etDecisionEvent\022.\n\010metadata\030\001 \001(\0132\034.janu"
    "s.packet.PacketMetadata\022&\n\007verdict\030\002 \001(\016"
    "2\025.janus.common.Verdict\022\017\n\007flagged\030\003 \001(\010"
    "\022\021\n\tinspected\030\004 \001(\010\022(\n\trule_hits\030\005 \003(\0132\025"
    ".janus.common.RuleHit\022\022\n\nmatch_info\030\006 \001("
    "\t\022\030\n\020detection_source\030\007 \001(\t\0227\n\020processin"
    "g_trace\030\010 \003(\0132\035.janus.common.ProcessingS"
    "tamp\022 \n\030end_to_end_processing_us\030\t \001(\004\022\021"
    "\n\tnode_name\030\n \001(\t\022\026\n\016container_name\030\013 \001("
    "\t\022\030\n\020blacklist_ip_hit\030\014 \001(\010\022\032\n\022blacklist"
    "_port_hit\030\r \001(\010\022\030\n\020protocol_blocked\030\016 \001("
    "\010b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_janus_5fpacket_2eproto_deps[1] = {
        &::descriptor_table_janus_5fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_janus_5fpacket_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_janus_5fpacket_2eproto = {
    false,
    false,
    969,
    descriptor_table_protodef_janus_5fpacket_2eproto,
    "janus_packet.proto",
    &descriptor_table_janus_5fpacket_2eproto_once,
    descriptor_table_janus_5fpacket_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_janus_5fpacket_2eproto::offsets,
    file_level_enum_descriptors_janus_5fpacket_2eproto,
    file_level_service_descriptors_janus_5fpacket_2eproto,
};
namespace janus {
namespace packet {
// ===================================================================

class PacketMetadata::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PacketMetadata>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_._has_bits_);
};

void PacketMetadata::clear_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.source_ != nullptr) _impl_.source_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
void PacketMetadata::clear_destination() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.destination_ != nullptr) _impl_.destination_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
PacketMetadata::PacketMetadata(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PacketMetadata_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:janus.packet.PacketMetadata)
}
PROTOBUF_NDEBUG_INLINE PacketMetadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::janus::packet::PacketMetadata& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        event_id_(arena, from.event_id_) {}

PacketMetadata::PacketMetadata(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PacketMetadata& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PacketMetadata_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PacketMetadata* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.source_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.source_)
                : nullptr;
  _impl_.destination_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.destination_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, packet_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, packet_id_),
           offsetof(Impl_, is_reassembled_) -
               offsetof(Impl_, packet_id_) +
               sizeof(Impl_::is_reassembled_));

  // @@protoc_insertion_point(copy_constructor:janus.packet.PacketMetadata)
}
PROTOBUF_NDEBUG_INLINE PacketMetadata::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        event_id_(arena) {}

inline void PacketMetadata::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, source_),
           0,
           offsetof(Impl_, is_reassembled_) -
               offsetof(Impl_, source_) +
               sizeof(Impl_::is_reassembled_));
}
PacketMetadata::~PacketMetadata() {
  // @@protoc_insertion_point(destructor:janus.packet.PacketMetadata)
  SharedDtor(*this);
}
inline void PacketMetadata::SharedDtor(MessageLite& self) {
  PacketMetadata& this_ = static_cast<PacketMetadata&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.event_id_.Destroy();
  delete this_._impl_.source_;
  delete this_._impl_.destination_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PacketMetadata::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PacketMetadata(arena);
}
constexpr auto PacketMetadata::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PacketMetadata),
                                            alignof(PacketMetadata));
}
constexpr auto PacketMetadata::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PacketMetadata_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PacketMetadata::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PacketMetadata>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PacketMetadata::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PacketMetadata>(), &PacketMetadata::ByteSizeLong,
              &PacketMetadata::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_._cached_size_),
          false,
      },
      &PacketMetadata::kDescriptorMethods,
      &descriptor_table_janus_5fpacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PacketMetadata_class_data_ =
        PacketMetadata::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PacketMetadata::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PacketMetadata_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PacketMetadata_class_data_.tc_table);
  return PacketMetadata_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 11, 2, 52, 2>
PacketMetadata::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_._has_bits_),
    0, // no _extensions_
    11, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294965248,  // skipmap
    offsetof(decltype(_table_), field_entries),
    11,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PacketMetadata_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::janus::packet::PacketMetadata>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string event_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.event_id_)}},
    // uint32 packet_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketMetadata, _impl_.packet_id_), 3>(),
     {16, 3, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.packet_id_)}},
    // uint32 queue_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketMetadata, _impl_.queue_id_), 4>(),
     {24, 4, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.queue_id_)}},
    // uint64 ts_unix_ms = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PacketMetadata, _impl_.ts_unix_ms_), 5>(),
     {32, 5, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.ts_unix_ms_)}},
    // uint32 payload_length = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketMetadata, _impl_.payload_length_), 6>(),
     {40, 6, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.payload_length_)}},
    // uint32 total_length = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketMetadata, _impl_.total_length_), 7>(),
     {48, 7, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.total_length_)}},
    // .janus.common.Protocol protocol = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketMetadata, _impl_.protocol_), 8>(),
     {56, 8, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.protocol_)}},
    // .janus.common.Endpoint source = 8;
    {::_pbi::TcParser::FastMtS1,
     {66, 1, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.source_)}},
    // .janus.common.Endpoint destination = 9;
    {::_pbi::TcParser::FastMtS1,
     {74, 2, 1,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.destination_)}},
    // bool is_fragmented = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketMetadata, _impl_.is_fragmented_), 9>(),
     {80, 9, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.is_fragmented_)}},
    // bool is_reassembled = 11;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketMetadata, _impl_.is_reassembled_), 10>(),
     {88, 10, 0,
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.is_reassembled_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string event_id = 1;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.event_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 packet_id = 2;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.packet_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 queue_id = 3;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.queue_id_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint64 ts_unix_ms = 4;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.ts_unix_ms_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint32 payload_length = 5;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.payload_length_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 total_length = 6;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.total_length_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .janus.common.Protocol protocol = 7;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.protocol_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .janus.common.Endpoint source = 8;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.source_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .janus.common.Endpoint destination = 9;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.destination_), _Internal::kHasBitsOffset + 2, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // bool is_fragmented = 10;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.is_fragmented_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool is_reassembled = 11;
    {PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.is_reassembled_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::janus::common::Endpoint>()},
      {::_pbi::TcParser::GetTable<::janus::common::Endpoint>()},
  }},
  {{
    "\33\10\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "janus.packet.PacketMetadata"
    "event_id"
  }},
};
PROTOBUF_NOINLINE void PacketMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:janus.packet.PacketMetadata)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.event_id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.source_ != nullptr);
      _impl_.source_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.destination_ != nullptr);
      _impl_.destination_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f8U)) {
    ::memset(&_impl_.packet_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.total_length_) -
        reinterpret_cast<char*>(&_impl_.packet_id_)) + sizeof(_impl_.total_length_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    ::memset(&_impl_.protocol_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_reassembled_) -
        reinterpret_cast<char*>(&_impl_.protocol_)) + sizeof(_impl_.is_reassembled_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PacketMetadata::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PacketMetadata& this_ = static_cast<const PacketMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PacketMetadata::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PacketMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:janus.packet.PacketMetadata)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string event_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_event_id().empty()) {
      const ::std::string& _s = this_._internal_event_id();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PacketMetadata.event_id");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint32 packet_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_packet_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_packet_id(), target);
    }
  }

  // uint32 queue_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_queue_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          3, this_._internal_queue_id(), target);
    }
  }

  // uint64 ts_unix_ms = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_ts_unix_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_ts_unix_ms(), target);
    }
  }

  // uint32 payload_length = 5;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_payload_length() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          5, this_._internal_payload_length(), target);
    }
  }

  // uint32 total_length = 6;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_total_length() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          6, this_._internal_total_length(), target);
    }
  }

  // .janus.common.Protocol protocol = 7;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_protocol() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          7, this_._internal_protocol(), target);
    }
  }

  // .janus.common.Endpoint source = 8;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        8, *this_._impl_.source_, this_._impl_.source_->GetCachedSize(), target,
        stream);
  }

  // .janus.common.Endpoint destination = 9;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        9, *this_._impl_.destination_, this_._impl_.destination_->GetCachedSize(), target,
        stream);
  }

  // bool is_fragmented = 10;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_is_fragmented() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          10, this_._internal_is_fragmented(), target);
    }
  }

  // bool is_reassembled = 11;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_is_reassembled() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          11, this_._internal_is_reassembled(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:janus.packet.PacketMetadata)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PacketMetadata::ByteSizeLong(const MessageLite& base) {
  const PacketMetadata& this_ = static_cast<const PacketMetadata&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PacketMetadata::ByteSizeLong() const {
  const PacketMetadata& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:janus.packet.PacketMetadata)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string event_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_event_id().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_event_id());
      }
    }
    // .janus.common.Endpoint source = 8;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.source_);
    }
    // .janus.common.Endpoint destination = 9;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.destination_);
    }
    // uint32 packet_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_packet_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_packet_id());
      }
    }
    // uint32 queue_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_queue_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_queue_id());
      }
    }
    // uint64 ts_unix_ms = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_ts_unix_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_ts_unix_ms());
      }
    }
    // uint32 payload_length = 5;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_payload_length() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_payload_length());
      }
    }
    // uint32 total_length = 6;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_total_length() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_total_length());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    // .janus.common.Protocol protocol = 7;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_protocol() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_protocol());
      }
    }
    // bool is_fragmented = 10;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_is_fragmented() != 0) {
        total_size += 2;
      }
    }
    // bool is_reassembled = 11;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_is_reassembled() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PacketMetadata::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PacketMetadata*>(&to_msg);
  auto& from = static_cast<const PacketMetadata&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:janus.packet.PacketMetadata)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_event_id().empty()) {
        _this->_internal_set_event_id(from._internal_event_id());
      } else {
        if (_this->_impl_.event_id_.IsDefault()) {
          _this->_internal_set_event_id("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.source_ != nullptr);
      if (_this->_impl_.source_ == nullptr) {
        _this->_impl_.source_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.source_);
      } else {
        _this->_impl_.source_->MergeFrom(*from._impl_.source_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.destination_ != nullptr);
      if (_this->_impl_.destination_ == nullptr) {
        _this->_impl_.destination_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.destination_);
      } else {
        _this->_impl_.destination_->MergeFrom(*from._impl_.destination_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_packet_id() != 0) {
        _this->_impl_.packet_id_ = from._impl_.packet_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_queue_id() != 0) {
        _this->_impl_.queue_id_ = from._impl_.queue_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_ts_unix_ms() != 0) {
        _this->_impl_.ts_unix_ms_ = from._impl_.ts_unix_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_payload_length() != 0) {
        _this->_impl_.payload_length_ = from._impl_.payload_length_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_total_length() != 0) {
        _this->_impl_.total_length_ = from._impl_.total_length_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_protocol() != 0) {
        _this->_impl_.protocol_ = from._impl_.protocol_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_is_fragmented() != 0) {
        _this->_impl_.is_fragmented_ = from._impl_.is_fragmented_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_is_reassembled() != 0) {
        _this->_impl_.is_reassembled_ = from._impl_.is_reassembled_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PacketMetadata::CopyFrom(const PacketMetadata& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:janus.packet.PacketMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PacketMetadata::InternalSwap(PacketMetadata* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.event_id_, &other->_impl_.event_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.is_reassembled_)
      + sizeof(PacketMetadata::_impl_.is_reassembled_)
      - PROTOBUF_FIELD_OFFSET(PacketMetadata, _impl_.source_)>(
          reinterpret_cast<char*>(&_impl_.source_),
          reinterpret_cast<char*>(&other->_impl_.source_));
}

::google::protobuf::Metadata PacketMetadata::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PreprocessingMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PreprocessingMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_._has_bits_);
};

PreprocessingMessage::PreprocessingMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PreprocessingMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:janus.packet.PreprocessingMessage)
}
PROTOBUF_NDEBUG_INLINE PreprocessingMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::janus::packet::PreprocessingMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        parser_status_(arena, from.parser_status_),
        parser_notes_(arena, from.parser_notes_),
        payload_preview_(arena, from.payload_preview_) {}

PreprocessingMessage::PreprocessingMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PreprocessingMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PreprocessingMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PreprocessingMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.metadata_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.metadata_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:janus.packet.PreprocessingMessage)
}
PROTOBUF_NDEBUG_INLINE PreprocessingMessage::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        parser_status_(arena),
        parser_notes_(arena),
        payload_preview_(arena) {}

inline void PreprocessingMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.metadata_ = {};
}
PreprocessingMessage::~PreprocessingMessage() {
  // @@protoc_insertion_point(destructor:janus.packet.PreprocessingMessage)
  SharedDtor(*this);
}
inline void PreprocessingMessage::SharedDtor(MessageLite& self) {
  PreprocessingMessage& this_ = static_cast<PreprocessingMessage&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.parser_status_.Destroy();
  this_._impl_.parser_notes_.Destroy();
  this_._impl_.payload_preview_.Destroy();
  delete this_._impl_.metadata_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PreprocessingMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PreprocessingMessage(arena);
}
constexpr auto PreprocessingMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PreprocessingMessage),
                                            alignof(PreprocessingMessage));
}
constexpr auto PreprocessingMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PreprocessingMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PreprocessingMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PreprocessingMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PreprocessingMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PreprocessingMessage>(), &PreprocessingMessage::ByteSizeLong,
              &PreprocessingMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_._cached_size_),
          false,
      },
      &PreprocessingMessage::kDescriptorMethods,
      &descriptor_table_janus_5fpacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PreprocessingMessage_class_data_ =
        PreprocessingMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PreprocessingMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PreprocessingMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PreprocessingMessage_class_data_.tc_table);
  return PreprocessingMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 67, 2>
PreprocessingMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PreprocessingMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::janus::packet::PreprocessingMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes payload_preview = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 2, 0,
      PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.payload_preview_)}},
    // .janus.packet.PacketMetadata metadata = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 3, 0,
      PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.metadata_)}},
    // string parser_status = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.parser_status_)}},
    // string parser_notes = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.parser_notes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .janus.packet.PacketMetadata metadata = 1;
    {PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.metadata_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string parser_status = 2;
    {PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.parser_status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string parser_notes = 3;
    {PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.parser_notes_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes payload_preview = 4;
    {PROTOBUF_FIELD_OFFSET(PreprocessingMessage, _impl_.payload_preview_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::janus::packet::PacketMetadata>()},
  }},
  {{
    "\41\0\15\14\0\0\0\0"
    "janus.packet.PreprocessingMessage"
    "parser_status"
    "parser_notes"
  }},
};
PROTOBUF_NOINLINE void PreprocessingMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:janus.packet.PreprocessingMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.parser_status_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.parser_notes_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.payload_preview_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.metadata_ != nullptr);
      _impl_.metadata_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PreprocessingMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PreprocessingMessage& this_ = static_cast<const PreprocessingMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PreprocessingMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PreprocessingMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:janus.packet.PreprocessingMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .janus.packet.PacketMetadata metadata = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.metadata_, this_._impl_.metadata_->GetCachedSize(), target,
        stream);
  }

  // string parser_status = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_parser_status().empty()) {
      const ::std::string& _s = this_._internal_parser_status();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PreprocessingMessage.parser_status");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string parser_notes = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_parser_notes().empty()) {
      const ::std::string& _s = this_._internal_parser_notes();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PreprocessingMessage.parser_notes");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // bytes payload_preview = 4;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_payload_preview().empty()) {
      const ::std::string& _s = this_._internal_payload_preview();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:janus.packet.PreprocessingMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PreprocessingMessage::ByteSizeLong(const MessageLite& base) {
  const PreprocessingMessage& this_ = static_cast<const PreprocessingMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PreprocessingMessage::ByteSizeLong() const {
  const PreprocessingMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:janus.packet.PreprocessingMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string parser_status = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_parser_status().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_parser_status());
      }
    }
    // string parser_notes = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_parser_notes().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_parser_notes());
      }
    }
    // bytes payload_preview = 4;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_payload_preview().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_payload_preview());
      }
    }
    // .janus.packet.PacketMetadata metadata = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.metadata_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PreprocessingMessage::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PreprocessingMessage*>(&to_msg);
  auto& from = static_cast<const PreprocessingMessage&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:janus.packet.PreprocessingMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_parser_status().empty()) {
        _this->_internal_set_parser_status(from._internal_parser_status());
      } else {
        if (_this->_impl_.parser_status_.IsDefault()) {
          _this->_internal_set_parser_status("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_parser_notes().empty()) {
        _this->_internal_set_parser_notes(from._internal_parser_notes());
      } else {
        if (_this->_impl_.parser_notes_.IsDefault()) {
          _this->_internal_set_parser_notes("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_payload_preview().empty()) {
        _this->_internal_set_payload_preview(from._internal_payload_preview());
      } else {
        if (_this->_impl_.payload_preview_.IsDefault()) {
          _this->_internal_set_payload_preview("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.metadata_ != nullptr);
      if (_this->_impl_.metadata_ == nullptr) {
        _this->_impl_.metadata_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.metadata_);
      } else {
        _this->_impl_.metadata_->MergeFrom(*from._impl_.metadata_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PreprocessingMessage::CopyFrom(const PreprocessingMessage& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:janus.packet.PreprocessingMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PreprocessingMessage::InternalSwap(PreprocessingMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.parser_status_, &other->_impl_.parser_status_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.parser_notes_, &other->_impl_.parser_notes_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_preview_, &other->_impl_.payload_preview_, arena);
  swap(_impl_.metadata_, other->_impl_.metadata_);
}

::google::protobuf::Metadata PreprocessingMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PacketDecisionEvent::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PacketDecisionEvent>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_._has_bits_);
};

void PacketDecisionEvent::clear_rule_hits() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rule_hits_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
void PacketDecisionEvent::clear_processing_trace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.processing_trace_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
PacketDecisionEvent::PacketDecisionEvent(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PacketDecisionEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:janus.packet.PacketDecisionEvent)
}
PROTOBUF_NDEBUG_INLINE PacketDecisionEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::janus::packet::PacketDecisionEvent& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rule_hits_{visibility, arena, from.rule_hits_},
        processing_trace_{visibility, arena, from.processing_trace_},
        match_info_(arena, from.match_info_),
        detection_source_(arena, from.detection_source_),
        node_name_(arena, from.node_name_),
        container_name_(arena, from.container_name_) {}

PacketDecisionEvent::PacketDecisionEvent(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PacketDecisionEvent& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PacketDecisionEvent_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PacketDecisionEvent* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.metadata_ = (CheckHasBit(cached_has_bits, 0x00000040U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.metadata_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, verdict_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, verdict_),
           offsetof(Impl_, protocol_blocked_) -
               offsetof(Impl_, verdict_) +
               sizeof(Impl_::protocol_blocked_));

  // @@protoc_insertion_point(copy_constructor:janus.packet.PacketDecisionEvent)
}
PROTOBUF_NDEBUG_INLINE PacketDecisionEvent::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        rule_hits_{visibility, arena},
        processing_trace_{visibility, arena},
        match_info_(arena),
        detection_source_(arena),
        node_name_(arena),
        container_name_(arena) {}

inline void PacketDecisionEvent::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, metadata_),
           0,
           offsetof(Impl_, protocol_blocked_) -
               offsetof(Impl_, metadata_) +
               sizeof(Impl_::protocol_blocked_));
}
PacketDecisionEvent::~PacketDecisionEvent() {
  // @@protoc_insertion_point(destructor:janus.packet.PacketDecisionEvent)
  SharedDtor(*this);
}
inline void PacketDecisionEvent::SharedDtor(MessageLite& self) {
  PacketDecisionEvent& this_ = static_cast<PacketDecisionEvent&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.match_info_.Destroy();
  this_._impl_.detection_source_.Destroy();
  this_._impl_.node_name_.Destroy();
  this_._impl_.container_name_.Destroy();
  delete this_._impl_.metadata_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PacketDecisionEvent::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PacketDecisionEvent(arena);
}
constexpr auto PacketDecisionEvent::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.rule_hits_) +
          decltype(PacketDecisionEvent::_impl_.rule_hits_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.processing_trace_) +
          decltype(PacketDecisionEvent::_impl_.processing_trace_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(PacketDecisionEvent), alignof(PacketDecisionEvent), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PacketDecisionEvent::PlacementNew_,
                                 sizeof(PacketDecisionEvent),
                                 alignof(PacketDecisionEvent));
  }
}
constexpr auto PacketDecisionEvent::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PacketDecisionEvent_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PacketDecisionEvent::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PacketDecisionEvent>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PacketDecisionEvent::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PacketDecisionEvent>(), &PacketDecisionEvent::ByteSizeLong,
              &PacketDecisionEvent::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_._cached_size_),
          false,
      },
      &PacketDecisionEvent::kDescriptorMethods,
      &descriptor_table_janus_5fpacket_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PacketDecisionEvent_class_data_ =
        PacketDecisionEvent::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PacketDecisionEvent::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PacketDecisionEvent_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PacketDecisionEvent_class_data_.tc_table);
  return PacketDecisionEvent_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 14, 3, 98, 2>
PacketDecisionEvent::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_._has_bits_),
    0, // no _extensions_
    14, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294950912,  // skipmap
    offsetof(decltype(_table_), field_entries),
    14,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PacketDecisionEvent_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::janus::packet::PacketDecisionEvent>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .janus.packet.PacketMetadata metadata = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 6, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.metadata_)}},
    // .janus.common.Verdict verdict = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PacketDecisionEvent, _impl_.verdict_), 7>(),
     {16, 7, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.verdict_)}},
    // bool flagged = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketDecisionEvent, _impl_.flagged_), 8>(),
     {24, 8, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.flagged_)}},
    // bool inspected = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketDecisionEvent, _impl_.inspected_), 9>(),
     {32, 9, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.inspected_)}},
    // repeated .janus.common.RuleHit rule_hits = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 0, 1,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.rule_hits_)}},
    // string match_info = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 2, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.match_info_)}},
    // string detection_source = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 3, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.detection_source_)}},
    // repeated .janus.common.ProcessingStamp processing_trace = 8;
    {::_pbi::TcParser::FastMtR1,
     {66, 1, 2,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.processing_trace_)}},
    // uint64 end_to_end_processing_us = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PacketDecisionEvent, _impl_.end_to_end_processing_us_), 12>(),
     {72, 12, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.end_to_end_processing_us_)}},
    // string node_name = 10;
    {::_pbi::TcParser::FastUS1,
     {82, 4, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.node_name_)}},
    // string container_name = 11;
    {::_pbi::TcParser::FastUS1,
     {90, 5, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.container_name_)}},
    // bool blacklist_ip_hit = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketDecisionEvent, _impl_.blacklist_ip_hit_), 10>(),
     {96, 10, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.blacklist_ip_hit_)}},
    // bool blacklist_port_hit = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketDecisionEvent, _impl_.blacklist_port_hit_), 11>(),
     {104, 11, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.blacklist_port_hit_)}},
    // bool protocol_blocked = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PacketDecisionEvent, _impl_.protocol_blocked_), 13>(),
     {112, 13, 0,
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.protocol_blocked_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .janus.packet.PacketMetadata metadata = 1;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.metadata_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .janus.common.Verdict verdict = 2;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.verdict_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool flagged = 3;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.flagged_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool inspected = 4;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.inspected_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // repeated .janus.common.RuleHit rule_hits = 5;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.rule_hits_), _Internal::kHasBitsOffset + 0, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // string match_info = 6;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.match_info_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string detection_source = 7;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.detection_source_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .janus.common.ProcessingStamp processing_trace = 8;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.processing_trace_), _Internal::kHasBitsOffset + 1, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint64 end_to_end_processing_us = 9;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.end_to_end_processing_us_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string node_name = 10;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.node_name_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string container_name = 11;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.container_name_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool blacklist_ip_hit = 12;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.blacklist_ip_hit_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool blacklist_port_hit = 13;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.blacklist_port_hit_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bool protocol_blocked = 14;
    {PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.protocol_blocked_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::janus::packet::PacketMetadata>()},
      {::_pbi::TcParser::GetTable<::janus::common::RuleHit>()},
      {::_pbi::TcParser::GetTable<::janus::common::ProcessingStamp>()},
  }},
  {{
    "\40\0\0\0\0\0\12\20\0\0\11\16\0\0\0\0"
    "janus.packet.PacketDecisionEvent"
    "match_info"
    "detection_source"
    "node_name"
    "container_name"
  }},
};
PROTOBUF_NOINLINE void PacketDecisionEvent::Clear() {
// @@protoc_insertion_point(message_clear_start:janus.packet.PacketDecisionEvent)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.rule_hits_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.processing_trace_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.match_info_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.detection_source_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.node_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.container_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(_impl_.metadata_ != nullptr);
      _impl_.metadata_->Clear();
    }
  }
  _impl_.verdict_ = 0;
  if (BatchCheckHasBit(cached_has_bits, 0x00003f00U)) {
    ::memset(&_impl_.flagged_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.protocol_blocked_) -
        reinterpret_cast<char*>(&_impl_.flagged_)) + sizeof(_impl_.protocol_blocked_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PacketDecisionEvent::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PacketDecisionEvent& this_ = static_cast<const PacketDecisionEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PacketDecisionEvent::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PacketDecisionEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:janus.packet.PacketDecisionEvent)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .janus.packet.PacketMetadata metadata = 1;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.metadata_, this_._impl_.metadata_->GetCachedSize(), target,
        stream);
  }

  // .janus.common.Verdict verdict = 2;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_verdict() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_verdict(), target);
    }
  }

  // bool flagged = 3;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_flagged() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_flagged(), target);
    }
  }

  // bool inspected = 4;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_inspected() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          4, this_._internal_inspected(), target);
    }
  }

  // repeated .janus.common.RuleHit rule_hits = 5;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_rule_hits_size());
         i < n; i++) {
      const auto& repfield = this_._internal_rule_hits().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              5, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // string match_info = 6;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_match_info().empty()) {
      const ::std::string& _s = this_._internal_match_info();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PacketDecisionEvent.match_info");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // string detection_source = 7;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_detection_source().empty()) {
      const ::std::string& _s = this_._internal_detection_source();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PacketDecisionEvent.detection_source");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // repeated .janus.common.ProcessingStamp processing_trace = 8;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_processing_trace_size());
         i < n; i++) {
      const auto& repfield = this_._internal_processing_trace().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              8, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // uint64 end_to_end_processing_us = 9;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (this_._internal_end_to_end_processing_us() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          9, this_._internal_end_to_end_processing_us(), target);
    }
  }

  // string node_name = 10;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_node_name().empty()) {
      const ::std::string& _s = this_._internal_node_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PacketDecisionEvent.node_name");
      target = stream->WriteStringMaybeAliased(10, _s, target);
    }
  }

  // string container_name = 11;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_container_name().empty()) {
      const ::std::string& _s = this_._internal_container_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.packet.PacketDecisionEvent.container_name");
      target = stream->WriteStringMaybeAliased(11, _s, target);
    }
  }

  // bool blacklist_ip_hit = 12;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_blacklist_ip_hit() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          12, this_._internal_blacklist_ip_hit(), target);
    }
  }

  // bool blacklist_port_hit = 13;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (this_._internal_blacklist_port_hit() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          13, this_._internal_blacklist_port_hit(), target);
    }
  }

  // bool protocol_blocked = 14;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    if (this_._internal_protocol_blocked() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          14, this_._internal_protocol_blocked(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:janus.packet.PacketDecisionEvent)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PacketDecisionEvent::ByteSizeLong(const MessageLite& base) {
  const PacketDecisionEvent& this_ = static_cast<const PacketDecisionEvent&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PacketDecisionEvent::ByteSizeLong() const {
  const PacketDecisionEvent& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:janus.packet.PacketDecisionEvent)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated .janus.common.RuleHit rule_hits = 5;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_rule_hits_size();
      for (const auto& msg : this_._internal_rule_hits()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .janus.common.ProcessingStamp processing_trace = 8;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_processing_trace_size();
      for (const auto& msg : this_._internal_processing_trace()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string match_info = 6;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_match_info().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_match_info());
      }
    }
    // string detection_source = 7;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_detection_source().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_detection_source());
      }
    }
    // string node_name = 10;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_node_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_node_name());
      }
    }
    // string container_name = 11;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!this_._internal_container_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_container_name());
      }
    }
    // .janus.packet.PacketMetadata metadata = 1;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.metadata_);
    }
    // .janus.common.Verdict verdict = 2;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_verdict() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_verdict());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00003f00U)) {
    // bool flagged = 3;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_flagged() != 0) {
        total_size += 2;
      }
    }
    // bool inspected = 4;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_inspected() != 0) {
        total_size += 2;
      }
    }
    // bool blacklist_ip_hit = 12;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_blacklist_ip_hit() != 0) {
        total_size += 2;
      }
    }
    // bool blacklist_port_hit = 13;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (this_._internal_blacklist_port_hit() != 0) {
        total_size += 2;
      }
    }
    // uint64 end_to_end_processing_us = 9;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (this_._internal_end_to_end_processing_us() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_end_to_end_processing_us());
      }
    }
    // bool protocol_blocked = 14;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (this_._internal_protocol_blocked() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PacketDecisionEvent::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PacketDecisionEvent*>(&to_msg);
  auto& from = static_cast<const PacketDecisionEvent&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:janus.packet.PacketDecisionEvent)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_rule_hits()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_rule_hits());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_processing_trace()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_processing_trace());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_match_info().empty()) {
        _this->_internal_set_match_info(from._internal_match_info());
      } else {
        if (_this->_impl_.match_info_.IsDefault()) {
          _this->_internal_set_match_info("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_detection_source().empty()) {
        _this->_internal_set_detection_source(from._internal_detection_source());
      } else {
        if (_this->_impl_.detection_source_.IsDefault()) {
          _this->_internal_set_detection_source("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_node_name().empty()) {
        _this->_internal_set_node_name(from._internal_node_name());
      } else {
        if (_this->_impl_.node_name_.IsDefault()) {
          _this->_internal_set_node_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!from._internal_container_name().empty()) {
        _this->_internal_set_container_name(from._internal_container_name());
      } else {
        if (_this->_impl_.container_name_.IsDefault()) {
          _this->_internal_set_container_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      ABSL_DCHECK(from._impl_.metadata_ != nullptr);
      if (_this->_impl_.metadata_ == nullptr) {
        _this->_impl_.metadata_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.metadata_);
      } else {
        _this->_impl_.metadata_->MergeFrom(*from._impl_.metadata_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_verdict() != 0) {
        _this->_impl_.verdict_ = from._impl_.verdict_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00003f00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_flagged() != 0) {
        _this->_impl_.flagged_ = from._impl_.flagged_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_inspected() != 0) {
        _this->_impl_.inspected_ = from._impl_.inspected_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_blacklist_ip_hit() != 0) {
        _this->_impl_.blacklist_ip_hit_ = from._impl_.blacklist_ip_hit_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (from._internal_blacklist_port_hit() != 0) {
        _this->_impl_.blacklist_port_hit_ = from._impl_.blacklist_port_hit_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (from._internal_end_to_end_processing_us() != 0) {
        _this->_impl_.end_to_end_processing_us_ = from._impl_.end_to_end_processing_us_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (from._internal_protocol_blocked() != 0) {
        _this->_impl_.protocol_blocked_ = from._impl_.protocol_blocked_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PacketDecisionEvent::CopyFrom(const PacketDecisionEvent& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:janus.packet.PacketDecisionEvent)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PacketDecisionEvent::InternalSwap(PacketDecisionEvent* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.rule_hits_.InternalSwap(&other->_impl_.rule_hits_);
  _impl_.processing_trace_.InternalSwap(&other->_impl_.processing_trace_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.match_info_, &other->_impl_.match_info_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.detection_source_, &other->_impl_.detection_source_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.node_name_, &other->_impl_.node_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.container_name_, &other->_impl_.container_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.protocol_blocked_)
      + sizeof(PacketDecisionEvent::_impl_.protocol_blocked_)
      - PROTOBUF_FIELD_OFFSET(PacketDecisionEvent, _impl_.metadata_)>(
          reinterpret_cast<char*>(&_impl_.metadata_),
          reinterpret_cast<char*>(&other->_impl_.metadata_));
}

::google::protobuf::Metadata PacketDecisionEvent::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
}  // namespace janus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_janus_5fpacket_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
