// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: janus_common.proto
// Protobuf C++ Version: 6.33.1

#include "janus_common.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace janus {
namespace common {

inline constexpr RuleHit::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        rule_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rule_desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        offset_mode_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rule_id_{0},
        protocol_{static_cast< ::janus::common::Protocol >(0)},
        action_{static_cast< ::janus::common::RuleAction >(0)},
        offset_{0u},
        length_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR RuleHit::RuleHit(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(RuleHit_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RuleHitDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RuleHitDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RuleHitDefaultTypeInternal() {}
  union {
    RuleHit _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RuleHitDefaultTypeInternal _RuleHit_default_instance_;

inline constexpr ProcessingStamp::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        status_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        started_unix_ms_{::uint64_t{0u}},
        finished_unix_ms_{::uint64_t{0u}},
        duration_us_{::uint64_t{0u}},
        stage_{static_cast< ::janus::common::EngineStage >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR ProcessingStamp::ProcessingStamp(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProcessingStamp_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProcessingStampDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessingStampDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessingStampDefaultTypeInternal() {}
  union {
    ProcessingStamp _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessingStampDefaultTypeInternal _ProcessingStamp_default_instance_;

inline constexpr Endpoint::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Endpoint::Endpoint(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Endpoint_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct EndpointDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EndpointDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~EndpointDefaultTypeInternal() {}
  union {
    Endpoint _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EndpointDefaultTypeInternal _Endpoint_default_instance_;
}  // namespace common
}  // namespace janus
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_janus_5fcommon_2eproto[4];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_janus_5fcommon_2eproto = nullptr;
const ::uint32_t
    TableStruct_janus_5fcommon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::janus::common::Endpoint, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::janus::common::Endpoint, _impl_.ip_),
        PROTOBUF_FIELD_OFFSET(::janus::common::Endpoint, _impl_.port_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_._has_bits_),
        11, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.rule_id_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.rule_name_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.rule_desc_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.protocol_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.action_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.offset_mode_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.offset_),
        PROTOBUF_FIELD_OFFSET(::janus::common::RuleHit, _impl_.length_),
        3,
        0,
        1,
        4,
        5,
        2,
        6,
        7,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::janus::common::ProcessingStamp, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::janus::common::ProcessingStamp, _impl_.stage_),
        PROTOBUF_FIELD_OFFSET(::janus::common::ProcessingStamp, _impl_.started_unix_ms_),
        PROTOBUF_FIELD_OFFSET(::janus::common::ProcessingStamp, _impl_.finished_unix_ms_),
        PROTOBUF_FIELD_OFFSET(::janus::common::ProcessingStamp, _impl_.duration_us_),
        PROTOBUF_FIELD_OFFSET(::janus::common::ProcessingStamp, _impl_.status_),
        4,
        1,
        2,
        3,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::janus::common::Endpoint)},
        {7, sizeof(::janus::common::RuleHit)},
        {26, sizeof(::janus::common::ProcessingStamp)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::janus::common::_Endpoint_default_instance_._instance,
    &::janus::common::_RuleHit_default_instance_._instance,
    &::janus::common::_ProcessingStamp_default_instance_._instance,
};
const char descriptor_table_protodef_janus_5fcommon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022janus_common.proto\022\014janus.common\"$\n\010En"
    "dpoint\022\n\n\002ip\030\001 \001(\t\022\014\n\004port\030\002 \001(\r\"\311\001\n\007Rul"
    "eHit\022\017\n\007rule_id\030\001 \001(\005\022\021\n\trule_name\030\002 \001(\t"
    "\022\021\n\trule_desc\030\003 \001(\t\022(\n\010protocol\030\004 \001(\0162\026."
    "janus.common.Protocol\022(\n\006action\030\005 \001(\0162\030."
    "janus.common.RuleAction\022\023\n\013offset_mode\030\006"
    " \001(\t\022\016\n\006offset\030\007 \001(\r\022\016\n\006length\030\010 \001(\r\"\223\001\n"
    "\017ProcessingStamp\022(\n\005stage\030\001 \001(\0162\031.janus."
    "common.EngineStage\022\027\n\017started_unix_ms\030\002 "
    "\001(\004\022\030\n\020finished_unix_ms\030\003 \001(\004\022\023\n\013duratio"
    "n_us\030\004 \001(\004\022\016\n\006status\030\005 \001(\t*\201\001\n\010Protocol\022"
    "\030\n\024PROTOCOL_UNSPECIFIED\020\000\022\020\n\014PROTOCOL_AN"
    "Y\020\001\022\020\n\014PROTOCOL_TCP\020\002\022\020\n\014PROTOCOL_UDP\020\003\022"
    "\021\n\rPROTOCOL_HTTP\020\004\022\022\n\016PROTOCOL_OTHER\020\005*G"
    "\n\007Verdict\022\027\n\023VERDICT_UNSPECIFIED\020\000\022\021\n\rVE"
    "RDICT_ALLOW\020\001\022\020\n\014VERDICT_DROP\020\002*m\n\nRuleA"
    "ction\022\033\n\027RULE_ACTION_UNSPECIFIED\020\000\022\025\n\021RU"
    "LE_ACTION_ALLOW\020\001\022\024\n\020RULE_ACTION_FLAG\020\002\022"
    "\025\n\021RULE_ACTION_BLOCK\020\003*\236\002\n\013EngineStage\022\034"
    "\n\030ENGINE_STAGE_UNSPECIFIED\020\000\022\033\n\027ENGINE_S"
    "TAGE_PREPROCESS\020\001\022\027\n\023ENGINE_STAGE_POLICY"
    "\020\002\022\036\n\032ENGINE_STAGE_VECTOR_FILTER\020\003\022\026\n\022EN"
    "GINE_STAGE_REGEX\020\004\022\024\n\020ENGINE_STAGE_AHO\020\005"
    "\022\024\n\020ENGINE_STAGE_DPI\020\006\022\036\n\032ENGINE_STAGE_E"
    "NCAPSULATION\020\007\022\035\n\031ENGINE_STAGE_TRANSMISS"
    "ION\020\010\022\030\n\024ENGINE_STAGE_LOGGING\020\tb\006proto3"
};
static ::absl::once_flag descriptor_table_janus_5fcommon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_janus_5fcommon_2eproto = {
    false,
    false,
    1039,
    descriptor_table_protodef_janus_5fcommon_2eproto,
    "janus_common.proto",
    &descriptor_table_janus_5fcommon_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_janus_5fcommon_2eproto::offsets,
    file_level_enum_descriptors_janus_5fcommon_2eproto,
    file_level_service_descriptors_janus_5fcommon_2eproto,
};
namespace janus {
namespace common {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Protocol_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_janus_5fcommon_2eproto);
  return file_level_enum_descriptors_janus_5fcommon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Protocol_internal_data_[] = {
    393216u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Verdict_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_janus_5fcommon_2eproto);
  return file_level_enum_descriptors_janus_5fcommon_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t Verdict_internal_data_[] = {
    196608u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RuleAction_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_janus_5fcommon_2eproto);
  return file_level_enum_descriptors_janus_5fcommon_2eproto[2];
}
PROTOBUF_CONSTINIT const uint32_t RuleAction_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EngineStage_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_janus_5fcommon_2eproto);
  return file_level_enum_descriptors_janus_5fcommon_2eproto[3];
}
PROTOBUF_CONSTINIT const uint32_t EngineStage_internal_data_[] = {
    655360u, 0u, };
// ===================================================================

class Endpoint::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Endpoint>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Endpoint, _impl_._has_bits_);
};

Endpoint::Endpoint(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Endpoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:janus.common.Endpoint)
}
PROTOBUF_NDEBUG_INLINE Endpoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::janus::common::Endpoint& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        ip_(arena, from.ip_) {}

Endpoint::Endpoint(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Endpoint& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Endpoint_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Endpoint* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.port_ = from._impl_.port_;

  // @@protoc_insertion_point(copy_constructor:janus.common.Endpoint)
}
PROTOBUF_NDEBUG_INLINE Endpoint::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        ip_(arena) {}

inline void Endpoint::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.port_ = {};
}
Endpoint::~Endpoint() {
  // @@protoc_insertion_point(destructor:janus.common.Endpoint)
  SharedDtor(*this);
}
inline void Endpoint::SharedDtor(MessageLite& self) {
  Endpoint& this_ = static_cast<Endpoint&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.ip_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Endpoint::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Endpoint(arena);
}
constexpr auto Endpoint::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Endpoint),
                                            alignof(Endpoint));
}
constexpr auto Endpoint::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Endpoint_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Endpoint::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Endpoint>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Endpoint::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Endpoint>(), &Endpoint::ByteSizeLong,
              &Endpoint::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Endpoint, _impl_._cached_size_),
          false,
      },
      &Endpoint::kDescriptorMethods,
      &descriptor_table_janus_5fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Endpoint_class_data_ =
        Endpoint::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Endpoint::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Endpoint_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Endpoint_class_data_.tc_table);
  return Endpoint_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 32, 2>
Endpoint::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Endpoint, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Endpoint_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::janus::common::Endpoint>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Endpoint, _impl_.port_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(Endpoint, _impl_.port_)}},
    // string ip = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(Endpoint, _impl_.ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string ip = 1;
    {PROTOBUF_FIELD_OFFSET(Endpoint, _impl_.ip_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 port = 2;
    {PROTOBUF_FIELD_OFFSET(Endpoint, _impl_.port_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\25\2\0\0\0\0\0\0"
    "janus.common.Endpoint"
    "ip"
  }},
};
PROTOBUF_NOINLINE void Endpoint::Clear() {
// @@protoc_insertion_point(message_clear_start:janus.common.Endpoint)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.ip_.ClearNonDefaultToEmpty();
  }
  _impl_.port_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Endpoint::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Endpoint& this_ = static_cast<const Endpoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Endpoint::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Endpoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:janus.common.Endpoint)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string ip = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_ip().empty()) {
      const ::std::string& _s = this_._internal_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.common.Endpoint.ip");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint32 port = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_port() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          2, this_._internal_port(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:janus.common.Endpoint)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Endpoint::ByteSizeLong(const MessageLite& base) {
  const Endpoint& this_ = static_cast<const Endpoint&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Endpoint::ByteSizeLong() const {
  const Endpoint& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:janus.common.Endpoint)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string ip = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_ip());
      }
    }
    // uint32 port = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_port() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_port());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Endpoint::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Endpoint*>(&to_msg);
  auto& from = static_cast<const Endpoint&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:janus.common.Endpoint)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_ip().empty()) {
        _this->_internal_set_ip(from._internal_ip());
      } else {
        if (_this->_impl_.ip_.IsDefault()) {
          _this->_internal_set_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_port() != 0) {
        _this->_impl_.port_ = from._impl_.port_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Endpoint::CopyFrom(const Endpoint& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:janus.common.Endpoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Endpoint::InternalSwap(Endpoint* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ip_, &other->_impl_.ip_, arena);
  swap(_impl_.port_, other->_impl_.port_);
}

::google::protobuf::Metadata Endpoint::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RuleHit::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<RuleHit>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(RuleHit, _impl_._has_bits_);
};

RuleHit::RuleHit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RuleHit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:janus.common.RuleHit)
}
PROTOBUF_NDEBUG_INLINE RuleHit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::janus::common::RuleHit& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        rule_name_(arena, from.rule_name_),
        rule_desc_(arena, from.rule_desc_),
        offset_mode_(arena, from.offset_mode_) {}

RuleHit::RuleHit(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const RuleHit& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, RuleHit_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RuleHit* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, rule_id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, rule_id_),
           offsetof(Impl_, length_) -
               offsetof(Impl_, rule_id_) +
               sizeof(Impl_::length_));

  // @@protoc_insertion_point(copy_constructor:janus.common.RuleHit)
}
PROTOBUF_NDEBUG_INLINE RuleHit::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        rule_name_(arena),
        rule_desc_(arena),
        offset_mode_(arena) {}

inline void RuleHit::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, rule_id_),
           0,
           offsetof(Impl_, length_) -
               offsetof(Impl_, rule_id_) +
               sizeof(Impl_::length_));
}
RuleHit::~RuleHit() {
  // @@protoc_insertion_point(destructor:janus.common.RuleHit)
  SharedDtor(*this);
}
inline void RuleHit::SharedDtor(MessageLite& self) {
  RuleHit& this_ = static_cast<RuleHit&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.rule_name_.Destroy();
  this_._impl_.rule_desc_.Destroy();
  this_._impl_.offset_mode_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL RuleHit::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) RuleHit(arena);
}
constexpr auto RuleHit::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RuleHit),
                                            alignof(RuleHit));
}
constexpr auto RuleHit::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_RuleHit_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &RuleHit::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<RuleHit>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &RuleHit::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<RuleHit>(), &RuleHit::ByteSizeLong,
              &RuleHit::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(RuleHit, _impl_._cached_size_),
          false,
      },
      &RuleHit::kDescriptorMethods,
      &descriptor_table_janus_5fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull RuleHit_class_data_ =
        RuleHit::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
RuleHit::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&RuleHit_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(RuleHit_class_data_.tc_table);
  return RuleHit_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 66, 2>
RuleHit::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(RuleHit, _impl_._has_bits_),
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    RuleHit_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::janus::common::RuleHit>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 length = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RuleHit, _impl_.length_), 7>(),
     {64, 7, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.length_)}},
    // int32 rule_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RuleHit, _impl_.rule_id_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_id_)}},
    // string rule_name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_name_)}},
    // string rule_desc = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_desc_)}},
    // .janus.common.Protocol protocol = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RuleHit, _impl_.protocol_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.protocol_)}},
    // .janus.common.RuleAction action = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RuleHit, _impl_.action_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.action_)}},
    // string offset_mode = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 2, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.offset_mode_)}},
    // uint32 offset = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(RuleHit, _impl_.offset_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.offset_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 rule_id = 1;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string rule_name = 2;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string rule_desc = 3;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_desc_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .janus.common.Protocol protocol = 4;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.protocol_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .janus.common.RuleAction action = 5;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.action_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string offset_mode = 6;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.offset_mode_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 offset = 7;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.offset_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // uint32 length = 8;
    {PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.length_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\24\0\11\11\0\0\13\0\0\0\0\0\0\0\0\0"
    "janus.common.RuleHit"
    "rule_name"
    "rule_desc"
    "offset_mode"
  }},
};
PROTOBUF_NOINLINE void RuleHit::Clear() {
// @@protoc_insertion_point(message_clear_start:janus.common.RuleHit)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.rule_name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.rule_desc_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.offset_mode_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000f8U)) {
    ::memset(&_impl_.rule_id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.length_) -
        reinterpret_cast<char*>(&_impl_.rule_id_)) + sizeof(_impl_.length_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL RuleHit::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const RuleHit& this_ = static_cast<const RuleHit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL RuleHit::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const RuleHit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:janus.common.RuleHit)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 rule_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_rule_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_rule_id(), target);
    }
  }

  // string rule_name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_rule_name().empty()) {
      const ::std::string& _s = this_._internal_rule_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.common.RuleHit.rule_name");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string rule_desc = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_rule_desc().empty()) {
      const ::std::string& _s = this_._internal_rule_desc();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.common.RuleHit.rule_desc");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // .janus.common.Protocol protocol = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_protocol() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          4, this_._internal_protocol(), target);
    }
  }

  // .janus.common.RuleAction action = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (this_._internal_action() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          5, this_._internal_action(), target);
    }
  }

  // string offset_mode = 6;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_offset_mode().empty()) {
      const ::std::string& _s = this_._internal_offset_mode();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.common.RuleHit.offset_mode");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // uint32 offset = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (this_._internal_offset() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          7, this_._internal_offset(), target);
    }
  }

  // uint32 length = 8;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (this_._internal_length() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          8, this_._internal_length(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:janus.common.RuleHit)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t RuleHit::ByteSizeLong(const MessageLite& base) {
  const RuleHit& this_ = static_cast<const RuleHit&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t RuleHit::ByteSizeLong() const {
  const RuleHit& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:janus.common.RuleHit)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // string rule_name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_rule_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rule_name());
      }
    }
    // string rule_desc = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_rule_desc().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_rule_desc());
      }
    }
    // string offset_mode = 6;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_offset_mode().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_offset_mode());
      }
    }
    // int32 rule_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_rule_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_rule_id());
      }
    }
    // .janus.common.Protocol protocol = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_protocol() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_protocol());
      }
    }
    // .janus.common.RuleAction action = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (this_._internal_action() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_action());
      }
    }
    // uint32 offset = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (this_._internal_offset() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_offset());
      }
    }
    // uint32 length = 8;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (this_._internal_length() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_length());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void RuleHit::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<RuleHit*>(&to_msg);
  auto& from = static_cast<const RuleHit&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:janus.common.RuleHit)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_rule_name().empty()) {
        _this->_internal_set_rule_name(from._internal_rule_name());
      } else {
        if (_this->_impl_.rule_name_.IsDefault()) {
          _this->_internal_set_rule_name("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_rule_desc().empty()) {
        _this->_internal_set_rule_desc(from._internal_rule_desc());
      } else {
        if (_this->_impl_.rule_desc_.IsDefault()) {
          _this->_internal_set_rule_desc("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_offset_mode().empty()) {
        _this->_internal_set_offset_mode(from._internal_offset_mode());
      } else {
        if (_this->_impl_.offset_mode_.IsDefault()) {
          _this->_internal_set_offset_mode("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_rule_id() != 0) {
        _this->_impl_.rule_id_ = from._impl_.rule_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_protocol() != 0) {
        _this->_impl_.protocol_ = from._impl_.protocol_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (from._internal_action() != 0) {
        _this->_impl_.action_ = from._impl_.action_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (from._internal_offset() != 0) {
        _this->_impl_.offset_ = from._impl_.offset_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (from._internal_length() != 0) {
        _this->_impl_.length_ = from._impl_.length_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void RuleHit::CopyFrom(const RuleHit& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:janus.common.RuleHit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RuleHit::InternalSwap(RuleHit* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rule_name_, &other->_impl_.rule_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rule_desc_, &other->_impl_.rule_desc_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.offset_mode_, &other->_impl_.offset_mode_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.length_)
      + sizeof(RuleHit::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(RuleHit, _impl_.rule_id_)>(
          reinterpret_cast<char*>(&_impl_.rule_id_),
          reinterpret_cast<char*>(&other->_impl_.rule_id_));
}

::google::protobuf::Metadata RuleHit::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ProcessingStamp::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ProcessingStamp>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_._has_bits_);
};

ProcessingStamp::ProcessingStamp(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessingStamp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:janus.common.ProcessingStamp)
}
PROTOBUF_NDEBUG_INLINE ProcessingStamp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::janus::common::ProcessingStamp& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        status_(arena, from.status_) {}

ProcessingStamp::ProcessingStamp(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ProcessingStamp& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProcessingStamp_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProcessingStamp* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, started_unix_ms_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, started_unix_ms_),
           offsetof(Impl_, stage_) -
               offsetof(Impl_, started_unix_ms_) +
               sizeof(Impl_::stage_));

  // @@protoc_insertion_point(copy_constructor:janus.common.ProcessingStamp)
}
PROTOBUF_NDEBUG_INLINE ProcessingStamp::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        status_(arena) {}

inline void ProcessingStamp::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, started_unix_ms_),
           0,
           offsetof(Impl_, stage_) -
               offsetof(Impl_, started_unix_ms_) +
               sizeof(Impl_::stage_));
}
ProcessingStamp::~ProcessingStamp() {
  // @@protoc_insertion_point(destructor:janus.common.ProcessingStamp)
  SharedDtor(*this);
}
inline void ProcessingStamp::SharedDtor(MessageLite& self) {
  ProcessingStamp& this_ = static_cast<ProcessingStamp&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.status_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ProcessingStamp::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ProcessingStamp(arena);
}
constexpr auto ProcessingStamp::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ProcessingStamp),
                                            alignof(ProcessingStamp));
}
constexpr auto ProcessingStamp::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProcessingStamp_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ProcessingStamp::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProcessingStamp>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProcessingStamp::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProcessingStamp>(), &ProcessingStamp::ByteSizeLong,
              &ProcessingStamp::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_._cached_size_),
          false,
      },
      &ProcessingStamp::kDescriptorMethods,
      &descriptor_table_janus_5fcommon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ProcessingStamp_class_data_ =
        ProcessingStamp::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ProcessingStamp::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProcessingStamp_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProcessingStamp_class_data_.tc_table);
  return ProcessingStamp_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 43, 2>
ProcessingStamp::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_._has_bits_),
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ProcessingStamp_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::janus::common::ProcessingStamp>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .janus.common.EngineStage stage = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ProcessingStamp, _impl_.stage_), 4>(),
     {8, 4, 0,
      PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.stage_)}},
    // uint64 started_unix_ms = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ProcessingStamp, _impl_.started_unix_ms_), 1>(),
     {16, 1, 0,
      PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.started_unix_ms_)}},
    // uint64 finished_unix_ms = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ProcessingStamp, _impl_.finished_unix_ms_), 2>(),
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.finished_unix_ms_)}},
    // uint64 duration_us = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ProcessingStamp, _impl_.duration_us_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.duration_us_)}},
    // string status = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 0, 0,
      PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.status_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .janus.common.EngineStage stage = 1;
    {PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.stage_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // uint64 started_unix_ms = 2;
    {PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.started_unix_ms_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 finished_unix_ms = 3;
    {PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.finished_unix_ms_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 duration_us = 4;
    {PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.duration_us_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // string status = 5;
    {PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.status_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\34\0\0\0\0\6\0\0"
    "janus.common.ProcessingStamp"
    "status"
  }},
};
PROTOBUF_NOINLINE void ProcessingStamp::Clear() {
// @@protoc_insertion_point(message_clear_start:janus.common.ProcessingStamp)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.status_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000001eU)) {
    ::memset(&_impl_.started_unix_ms_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.stage_) -
        reinterpret_cast<char*>(&_impl_.started_unix_ms_)) + sizeof(_impl_.stage_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ProcessingStamp::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ProcessingStamp& this_ = static_cast<const ProcessingStamp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ProcessingStamp::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ProcessingStamp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:janus.common.ProcessingStamp)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .janus.common.EngineStage stage = 1;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_stage() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_stage(), target);
    }
  }

  // uint64 started_unix_ms = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_started_unix_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_started_unix_ms(), target);
    }
  }

  // uint64 finished_unix_ms = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_finished_unix_ms() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          3, this_._internal_finished_unix_ms(), target);
    }
  }

  // uint64 duration_us = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_duration_us() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          4, this_._internal_duration_us(), target);
    }
  }

  // string status = 5;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_status().empty()) {
      const ::std::string& _s = this_._internal_status();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "janus.common.ProcessingStamp.status");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:janus.common.ProcessingStamp)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ProcessingStamp::ByteSizeLong(const MessageLite& base) {
  const ProcessingStamp& this_ = static_cast<const ProcessingStamp&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ProcessingStamp::ByteSizeLong() const {
  const ProcessingStamp& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:janus.common.ProcessingStamp)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // string status = 5;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_status().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_status());
      }
    }
    // uint64 started_unix_ms = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_started_unix_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_started_unix_ms());
      }
    }
    // uint64 finished_unix_ms = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_finished_unix_ms() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_finished_unix_ms());
      }
    }
    // uint64 duration_us = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_duration_us() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_duration_us());
      }
    }
    // .janus.common.EngineStage stage = 1;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_stage() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_stage());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ProcessingStamp::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ProcessingStamp*>(&to_msg);
  auto& from = static_cast<const ProcessingStamp&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:janus.common.ProcessingStamp)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_status().empty()) {
        _this->_internal_set_status(from._internal_status());
      } else {
        if (_this->_impl_.status_.IsDefault()) {
          _this->_internal_set_status("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_started_unix_ms() != 0) {
        _this->_impl_.started_unix_ms_ = from._impl_.started_unix_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_finished_unix_ms() != 0) {
        _this->_impl_.finished_unix_ms_ = from._impl_.finished_unix_ms_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_duration_us() != 0) {
        _this->_impl_.duration_us_ = from._impl_.duration_us_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_stage() != 0) {
        _this->_impl_.stage_ = from._impl_.stage_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ProcessingStamp::CopyFrom(const ProcessingStamp& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:janus.common.ProcessingStamp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProcessingStamp::InternalSwap(ProcessingStamp* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.status_, &other->_impl_.status_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.stage_)
      + sizeof(ProcessingStamp::_impl_.stage_)
      - PROTOBUF_FIELD_OFFSET(ProcessingStamp, _impl_.started_unix_ms_)>(
          reinterpret_cast<char*>(&_impl_.started_unix_ms_),
          reinterpret_cast<char*>(&other->_impl_.started_unix_ms_));
}

::google::protobuf::Metadata ProcessingStamp::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace common
}  // namespace janus
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_janus_5fcommon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
